package principal;

import auxiliar.validaLogin;
import auxiliar.Data;
import Cadastro.*;
import RelatorioForm.*;
import java.text.SimpleDateFormat;
import java.awt.event.ActionEvent;
import javax.swing.JOptionPane;
import auxiliar.conexao;
import auxiliar.validaCadCli;
import  RelatorioJava.relacaoSuspensosVencidos;
//import java.awt.Color;


/*
 * telaPrincipal.java
 *
 * Created on 5 de Setembro de 2009, 16:44
 */



/**
 *
 * @author  ayrton monier
 */
public class telaPrincipal extends javax.swing.JFrame {
    protected static boolean trocaUser;
    SimpleDateFormat horaformatada = new SimpleDateFormat("HH:mm:ss");
    public static conexao con_telaPrincipal;
    public static boolean aberto = true;
    public static int contaTempoBloqueio;
    public static int qtdSuspensosExpirados;

    /** Creates new form telaPrincipal */
    public telaPrincipal() {
        initComponents();
        //inicia a tela maximizada
        this.setExtendedState(this.MAXIMIZED_BOTH);

        //da inicio ao meu relogio (atualiza a thread a cada 1000 milésimos ouseja 1 segundo)
        relogio.setDelay(1000);
        relogio.start();

        con_telaPrincipal = new conexao();
        con_telaPrincipal.conecta();

        //se o usuario for o administrador ou o gerente ele verifica os expirados
        if(validaLogin.USUARIO.equals("Administrador") || validaLogin.USUARIO.equals("Gerente"))
           verificaExpirados();

        else{
            painelSuspensao.setVisible(false);
        }

        //Atualiza hora e data
        Data.le_hora();
        Data.le_data();


        //mostra usuario
        lbUsuario.setText(validaLogin.USUARIO);

        //mostra hora do login
        mostraLogin.setText(validaLogin.HORA);

        lb_bloqueadoEm.setVisible(false);
        lb_contador.setVisible(false);
        lb_seg.setVisible(false);


        
     }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        relogio = new org.netbeans.examples.lib.timerbean.Timer();
        bloqueiaTela = new org.netbeans.examples.lib.timerbean.Timer();
        painelPrincipal = new javax.swing.JPanel();
        btCliente = new javax.swing.JButton();
        btSair = new javax.swing.JButton();
        btUsuario = new javax.swing.JButton();
        trocaUsuario = new javax.swing.JButton();
        btConfiguracao = new javax.swing.JButton();
        btBombona = new javax.swing.JButton();
        btIncinera = new javax.swing.JButton();
        ci = new javax.swing.JLabel();
        btRelatBombona = new javax.swing.JButton();
        btRelatInicineracao = new javax.swing.JButton();
        trocaSenhaOp = new javax.swing.JButton();
        informaSituacaoGeral = new javax.swing.JButton();
        lbAberto = new javax.swing.JLabel();
        informaSituacaoGeral1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lb_desenvolvidoPor = new javax.swing.JLabel();
        painelSuspensao = new javax.swing.JPanel();
        chamaSuspensos = new javax.swing.JButton();
        lbSuspeso = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        chamaSuspensos1 = new javax.swing.JButton();
        chamaSuspensos2 = new javax.swing.JButton();
        lb_bloqueadoEm = new javax.swing.JLabel();
        lb_contador = new javax.swing.JLabel();
        lb_seg = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        mostraData = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        mostraHora = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lbUsuario = new javax.swing.JLabel();
        painelTurno = new javax.swing.JPanel();
        mostraTurno = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        mostraLogin = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        nomeHost = new javax.swing.JLabel();
        barraMenuPrincipal = new javax.swing.JMenuBar();
        menuSistema = new javax.swing.JMenu();
        itemMenuCliente = new javax.swing.JMenuItem();
        ItemMenuUsuario = new javax.swing.JMenuItem();
        itemMenuBombona = new javax.swing.JMenuItem();
        itemMenuIncinerar = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JSeparator();
        itemMenuSair = new javax.swing.JMenuItem();
        menuRelatorio = new javax.swing.JMenu();
        menuRelatBombona = new javax.swing.JMenuItem();
        menuRelatIncineracao = new javax.swing.JMenuItem();
        menuRelatUserBombona = new javax.swing.JMenuItem();
        menuRelatUserIncineracao = new javax.swing.JMenuItem();
        menuLogUser = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        menuOpcoes = new javax.swing.JMenu();
        menuOpTocaUser = new javax.swing.JMenuItem();
        menuOpUser = new javax.swing.JMenu();
        menuOpUserSenha = new javax.swing.JMenuItem();
        menuUtilitarios = new javax.swing.JMenu();
        menuUtilCalc = new javax.swing.JMenuItem();
        menuUtilCalend = new javax.swing.JMenuItem();
        menuUtilRemot = new javax.swing.JMenuItem();
        munuSobre = new javax.swing.JMenu();
        itemMenuSisserq = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        relogio.addTimerListener(new org.netbeans.examples.lib.timerbean.TimerListener() {
            public void onTime(java.awt.event.ActionEvent evt) {
                relogioOnTime(evt);
            }
        });

        bloqueiaTela.addTimerListener(new org.netbeans.examples.lib.timerbean.TimerListener() {
            public void onTime(java.awt.event.ActionEvent evt) {
                bloqueiaTelaOnTime(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Tela principal - Sistema Serquip 1.0");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImages(null);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        painelPrincipal.setBackground(new java.awt.Color(0, 102, 0));
        painelPrincipal.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/clientes.png"))); // NOI18N
        btCliente.setToolTipText("Controle de clientes");
        btCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btClienteActionPerformed(evt);
            }
        });

        btSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/sair.png"))); // NOI18N
        btSair.setMnemonic('X');
        btSair.setToolTipText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        btUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/usuarios.png"))); // NOI18N
        btUsuario.setToolTipText("Controle de operadores");
        btUsuario.setAutoscrolls(true);
        btUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUsuarioActionPerformed(evt);
            }
        });

        trocaUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/troca_usuario.png"))); // NOI18N
        trocaUsuario.setToolTipText("Trocar de usuário");
        trocaUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trocaUsuarioActionPerformed(evt);
            }
        });

        btConfiguracao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/configuracao.png"))); // NOI18N
        btConfiguracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConfiguracaoActionPerformed(evt);
            }
        });

        btBombona.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/bombona.png"))); // NOI18N
        btBombona.setMnemonic('B');
        btBombona.setToolTipText("Controle de pesagem de bombonas");
        btBombona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBombonaActionPerformed(evt);
            }
        });

        btIncinera.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/incineracao.png"))); // NOI18N
        btIncinera.setMnemonic('I');
        btIncinera.setToolTipText("Controle de incineração de resíduos");
        btIncinera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btIncineraActionPerformed(evt);
            }
        });

        btRelatBombona.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/relatorioBombona.png"))); // NOI18N
        btRelatBombona.setToolTipText("Acompanhamento de pesagem de bombonas");
        btRelatBombona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRelatBombonaActionPerformed(evt);
            }
        });

        btRelatInicineracao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/relatInci.png"))); // NOI18N
        btRelatInicineracao.setToolTipText("Acompanhamento de incineração de resíduos");
        btRelatInicineracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRelatInicineracaoActionPerformed(evt);
            }
        });

        trocaSenhaOp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/senha.png"))); // NOI18N
        trocaSenhaOp.setToolTipText("Trocar senha");
        trocaSenhaOp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trocaSenhaOpActionPerformed(evt);
            }
        });

        informaSituacaoGeral.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/informacao.png"))); // NOI18N
        informaSituacaoGeral.setToolTipText("Informação geral atual");
        informaSituacaoGeral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                informaSituacaoGeralActionPerformed(evt);
            }
        });

        lbAberto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/aberto.png"))); // NOI18N
        lbAberto.setToolTipText("Bloquear parcialmente o sistema");
        lbAberto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbAbertoMouseClicked(evt);
            }
        });

        informaSituacaoGeral1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/manual.png"))); // NOI18N
        informaSituacaoGeral1.setToolTipText("Manual do usuário");
        informaSituacaoGeral1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                informaSituacaoGeral1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelPrincipalLayout = new javax.swing.GroupLayout(painelPrincipal);
        painelPrincipal.setLayout(painelPrincipalLayout);
        painelPrincipalLayout.setHorizontalGroup(
            painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btBombona, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btIncinera, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btRelatBombona, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btRelatInicineracao, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(trocaSenhaOp, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(trocaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btConfiguracao, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(informaSituacaoGeral, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(informaSituacaoGeral1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelPrincipalLayout.createSequentialGroup()
                        .addComponent(btSair, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 426, Short.MAX_VALUE)
                        .addComponent(lbAberto)
                        .addGap(27, 27, 27))
                    .addGroup(painelPrincipalLayout.createSequentialGroup()
                        .addComponent(ci)
                        .addContainerGap(533, Short.MAX_VALUE))))
        );
        painelPrincipalLayout.setVerticalGroup(
            painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btSair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lbAberto)
                        .addGroup(painelPrincipalLayout.createSequentialGroup()
                            .addComponent(ci)
                            .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(informaSituacaoGeral, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btConfiguracao, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(trocaUsuario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(trocaSenhaOp, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btRelatInicineracao, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btRelatBombona, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btIncinera, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btBombona, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btUsuario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btCliente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(informaSituacaoGeral1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        lb_desenvolvidoPor.setForeground(new java.awt.Color(153, 153, 153));
        lb_desenvolvidoPor.setText("Desenvolvido por Ayrton Monier");

        painelSuspensao.setBackground(new java.awt.Color(204, 204, 204));
        painelSuspensao.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 102, 0), null, new java.awt.Color(255, 255, 0)));

        chamaSuspensos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ok22.png"))); // NOI18N
        chamaSuspensos.setText("Ver");
        chamaSuspensos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chamaSuspensosActionPerformed(evt);
            }
        });

        lbSuspeso.setText("Qtd. de clientes:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel7.setText("Entre em contato para saber a respeito.");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/suspensaoVencida.png"))); // NOI18N
        jLabel2.setText("Cliente(s) com período de suspensão vencido");

        chamaSuspensos1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ativar_todos.png"))); // NOI18N
        chamaSuspensos1.setText("Ativar todos");
        chamaSuspensos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chamaSuspensos1ActionPerformed(evt);
            }
        });

        chamaSuspensos2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/imprimir22.png"))); // NOI18N
        chamaSuspensos2.setText("Imprimir lista");
        chamaSuspensos2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chamaSuspensos2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelSuspensaoLayout = new javax.swing.GroupLayout(painelSuspensao);
        painelSuspensao.setLayout(painelSuspensaoLayout);
        painelSuspensaoLayout.setHorizontalGroup(
            painelSuspensaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 446, Short.MAX_VALUE)
            .addGroup(painelSuspensaoLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(painelSuspensaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 402, Short.MAX_VALUE)
                    .addComponent(jLabel7)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelSuspensaoLayout.createSequentialGroup()
                        .addComponent(lbSuspeso)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 209, Short.MAX_VALUE)
                        .addGroup(painelSuspensaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(chamaSuspensos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(chamaSuspensos1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(chamaSuspensos2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        painelSuspensaoLayout.setVerticalGroup(
            painelSuspensaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelSuspensaoLayout.createSequentialGroup()
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addGap(20, 20, 20)
                .addComponent(chamaSuspensos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelSuspensaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(painelSuspensaoLayout.createSequentialGroup()
                        .addComponent(chamaSuspensos1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chamaSuspensos2))
                    .addComponent(lbSuspeso))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lb_bloqueadoEm.setText("Bloqueando em");

        lb_contador.setText("5");

        lb_seg.setText("Seg.");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lb_desenvolvidoPor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 497, Short.MAX_VALUE)
                        .addComponent(painelSuspensao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(lb_bloqueadoEm)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb_contador)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb_seg, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_contador)
                    .addComponent(lb_seg, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_bloqueadoEm))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 271, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lb_desenvolvidoPor)
                        .addContainerGap())
                    .addComponent(painelSuspensao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        mostraData.setFont(new java.awt.Font("Trebuchet MS", 1, 14));
        mostraData.setForeground(new java.awt.Color(0, 102, 0));
        mostraData.setText("Data:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mostraData, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(mostraData, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        mostraHora.setFont(new java.awt.Font("Trebuchet MS", 1, 14));
        mostraHora.setForeground(new java.awt.Color(0, 102, 0));
        mostraHora.setText("Hora Atual:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mostraHora)
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mostraHora)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        lbUsuario.setFont(new java.awt.Font("Trebuchet MS", 1, 14));
        lbUsuario.setForeground(new java.awt.Color(0, 102, 0));
        lbUsuario.setText("Usuário:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbUsuario)
                .addContainerGap(223, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbUsuario)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        painelTurno.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        painelTurno.setToolTipText("");
        painelTurno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                painelTurnoMouseEntered(evt);
            }
        });

        mostraTurno.setFont(new java.awt.Font("Trebuchet MS", 1, 14));
        mostraTurno.setForeground(new java.awt.Color(0, 102, 0));
        mostraTurno.setText("Turno:");

        javax.swing.GroupLayout painelTurnoLayout = new javax.swing.GroupLayout(painelTurno);
        painelTurno.setLayout(painelTurnoLayout);
        painelTurnoLayout.setHorizontalGroup(
            painelTurnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelTurnoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mostraTurno)
                .addContainerGap(83, Short.MAX_VALUE))
        );
        painelTurnoLayout.setVerticalGroup(
            painelTurnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelTurnoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mostraTurno)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel6.setToolTipText("Horário que você entrou no sistema");

        mostraLogin.setFont(new java.awt.Font("Trebuchet MS", 1, 14));
        mostraLogin.setForeground(new java.awt.Color(0, 102, 0));
        mostraLogin.setText("Hora do login:");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mostraLogin)
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mostraLogin)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jPanel5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel5.setToolTipText("IP desta máquina");

        nomeHost.setFont(new java.awt.Font("Trebuchet MS", 1, 14));
        nomeHost.setForeground(new java.awt.Color(0, 102, 0));
        nomeHost.setText("Host");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nomeHost)
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(nomeHost)
                .addContainerGap())
        );

        menuSistema.setMnemonic('S');
        menuSistema.setText("Sistema");
        menuSistema.setToolTipText("");

        itemMenuCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        itemMenuCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/clientes.png"))); // NOI18N
        itemMenuCliente.setMnemonic('C');
        itemMenuCliente.setText("Controle de clientes");
        itemMenuCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuClienteActionPerformed(evt);
            }
        });
        menuSistema.add(itemMenuCliente);

        ItemMenuUsuario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        ItemMenuUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/usuarios.png"))); // NOI18N
        ItemMenuUsuario.setMnemonic('U');
        ItemMenuUsuario.setText("Controle de operadores");
        ItemMenuUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemMenuUsuarioActionPerformed(evt);
            }
        });
        menuSistema.add(ItemMenuUsuario);

        itemMenuBombona.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        itemMenuBombona.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/bombona.png"))); // NOI18N
        itemMenuBombona.setMnemonic('B');
        itemMenuBombona.setText("Controle de pesagem de bombonas");
        itemMenuBombona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menuSistema.add(itemMenuBombona);

        itemMenuIncinerar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        itemMenuIncinerar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/incineracao.png"))); // NOI18N
        itemMenuIncinerar.setMnemonic('I');
        itemMenuIncinerar.setText("Controle de incineração de resíduos");
        itemMenuIncinerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuIncinerarActionPerformed(evt);
            }
        });
        menuSistema.add(itemMenuIncinerar);
        menuSistema.add(jSeparator3);

        itemMenuSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        itemMenuSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/sair.png"))); // NOI18N
        itemMenuSair.setMnemonic('S');
        itemMenuSair.setText("Sair");
        itemMenuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuSairActionPerformed(evt);
            }
        });
        menuSistema.add(itemMenuSair);

        barraMenuPrincipal.add(menuSistema);

        menuRelatorio.setMnemonic('R');
        menuRelatorio.setText("Relatórios");

        menuRelatBombona.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        menuRelatBombona.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/relatorioBombona.png"))); // NOI18N
        menuRelatBombona.setMnemonic('p');
        menuRelatBombona.setText("Acompanhamento de pesagem de bombonas");
        menuRelatBombona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRelatBombonaActionPerformed(evt);
            }
        });
        menuRelatorio.add(menuRelatBombona);

        menuRelatIncineracao.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        menuRelatIncineracao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/relatInci.png"))); // NOI18N
        menuRelatIncineracao.setMnemonic('i');
        menuRelatIncineracao.setText("Acompanhamento de incineração de resíduos");
        menuRelatIncineracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRelatIncineracaoActionPerformed(evt);
            }
        });
        menuRelatorio.add(menuRelatIncineracao);

        menuRelatUserBombona.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        menuRelatUserBombona.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/acompanhamento.png"))); // NOI18N
        menuRelatUserBombona.setMnemonic('m');
        menuRelatUserBombona.setText("Acompanhamento de pesagem de bombona por operador");
        menuRelatUserBombona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRelatUserBombonaActionPerformed(evt);
            }
        });
        menuRelatorio.add(menuRelatUserBombona);

        menuRelatUserIncineracao.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        menuRelatUserIncineracao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/acompanhamentoInci.png"))); // NOI18N
        menuRelatUserIncineracao.setMnemonic('n');
        menuRelatUserIncineracao.setText("Acompanhamento de incineração de resíduos por operador");
        menuRelatUserIncineracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRelatUserIncineracaoActionPerformed(evt);
            }
        });
        menuRelatorio.add(menuRelatUserIncineracao);

        menuLogUser.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        menuLogUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/acompanhaLog.png"))); // NOI18N
        menuLogUser.setText("Log de usuário");
        menuLogUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLogUserActionPerformed(evt);
            }
        });
        menuRelatorio.add(menuLogUser);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/informacao.png"))); // NOI18N
        jMenuItem1.setText("Informação geral atual");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed1(evt);
            }
        });
        menuRelatorio.add(jMenuItem1);

        barraMenuPrincipal.add(menuRelatorio);

        menuOpcoes.setMnemonic('O');
        menuOpcoes.setText("Opções");

        menuOpTocaUser.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        menuOpTocaUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/troca_usuario.png"))); // NOI18N
        menuOpTocaUser.setMnemonic('T');
        menuOpTocaUser.setText("Trocar de usuário");
        menuOpTocaUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuOpTocaUserActionPerformed(evt);
            }
        });
        menuOpcoes.add(menuOpTocaUser);

        menuOpUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/usuarios.png"))); // NOI18N
        menuOpUser.setMnemonic('U');
        menuOpUser.setText("Controle de operadores");

        menuOpUserSenha.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        menuOpUserSenha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/senha.png"))); // NOI18N
        menuOpUserSenha.setMnemonic('s');
        menuOpUserSenha.setText("Trocar senha");
        menuOpUserSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuOpUserSenhaActionPerformed(evt);
            }
        });
        menuOpUser.add(menuOpUserSenha);

        menuOpcoes.add(menuOpUser);

        barraMenuPrincipal.add(menuOpcoes);

        menuUtilitarios.setText("Utilitários");

        menuUtilCalc.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        menuUtilCalc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/calculadora.png"))); // NOI18N
        menuUtilCalc.setText("Calculadora");
        menuUtilCalc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuUtilCalcActionPerformed1(evt);
            }
        });
        menuUtilitarios.add(menuUtilCalc);

        menuUtilCalend.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, 0));
        menuUtilCalend.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/calendario.png"))); // NOI18N
        menuUtilCalend.setText("Calendário");
        menuUtilCalend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuUtilCalendActionPerformed1(evt);
            }
        });
        menuUtilitarios.add(menuUtilCalend);

        menuUtilRemot.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, 0));
        menuUtilRemot.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/vnc.jpg"))); // NOI18N
        menuUtilRemot.setText("Conexão Remota");
        menuUtilRemot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuUtilRemotActionPerformed(evt);
            }
        });
        menuUtilitarios.add(menuUtilRemot);

        barraMenuPrincipal.add(menuUtilitarios);

        munuSobre.setMnemonic('E');
        munuSobre.setText("Ajuda");

        itemMenuSisserq.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, 0));
        itemMenuSisserq.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/serquip.jpg"))); // NOI18N
        itemMenuSisserq.setMnemonic('S');
        itemMenuSisserq.setText("Sobre");
        itemMenuSisserq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuSisserqActionPerformed(evt);
            }
        });
        munuSobre.add(itemMenuSisserq);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/manual.png"))); // NOI18N
        jMenuItem2.setText("Manual do usuário");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        munuSobre.add(jMenuItem2);

        barraMenuPrincipal.add(munuSobre);

        setJMenuBar(barraMenuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(painelTurno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(painelPrincipal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(painelTurno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        java.awt.Dimension dialogSize = getSize();
        setLocation((screenSize.width-dialogSize.width)/2,(screenSize.height-dialogSize.height)/2);
    }// </editor-fold>//GEN-END:initComponents

    private void btUsuarioActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btUsuarioActionPerformed
        try{
            //instaci da classe cadastro usuario
            configuracoesDeUsuario cu = new configuracoesDeUsuario();

            //gerente não cadastra gerente
            if(validaLogin.USUARIO.equals("Gerente")){
                //JOptionPane.showMessageDialog(null, ""+validaLogin.USUARIO);
                cu.tipoUsuario.setEnabled(false);
           
            }

            //mostra a janela
            cu.setVisible(true);
        }

        catch(Exception e){
           JOptionPane.showMessageDialog(null, e);

        }
        
    }//GEN-LAST:event_btUsuarioActionPerformed

    private void btIncineraActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btIncineraActionPerformed
        //esconde botoes
        btBombona.setVisible(false);
        trocaUsuario.setVisible(false);
        btSair.setVisible(false);

        //chama tela cadastro de bombona
        CadastroIncineracao dialog = new CadastroIncineracao(new javax.swing.JFrame(), true);
        dialog.setVisible(true);
       
        //mostra botoes
        btBombona.setVisible(true);
        trocaUsuario.setVisible(true);
        btSair.setVisible(true);
    }//GEN-LAST:event_btIncineraActionPerformed

    private void jMenuItem1ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
       CadastroBombona dialog = new CadastroBombona(new javax.swing.JFrame(), true);
       dialog.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        confirmaSaida dialog = new confirmaSaida(new javax.swing.JFrame(), true);
        dialog.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    private void itemMenuClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuClienteActionPerformed
        new CadastroCliente().setVisible(true);
    }//GEN-LAST:event_itemMenuClienteActionPerformed

    private void btClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btClienteActionPerformed
        new CadastroCliente().setVisible(true);
    }//GEN-LAST:event_btClienteActionPerformed

    private void btBombonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBombonaActionPerformed

        btIncinera.setVisible(false);
        trocaUsuario.setVisible(false);
        btSair.setVisible(false);
        
        //chama tela cadastro de bombona
        CadastroBombona dialog = new CadastroBombona(new javax.swing.JFrame(), true);
        dialog.setVisible(true);
        
        btIncinera.setVisible(true);
        trocaUsuario.setVisible(true);
        btSair.setVisible(true);


    }//GEN-LAST:event_btBombonaActionPerformed

    private void itemMenuIncinerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuIncinerarActionPerformed
        CadastroIncineracao dialog = new CadastroIncineracao(new javax.swing.JFrame(), true);
        dialog.setVisible(true);
    }//GEN-LAST:event_itemMenuIncinerarActionPerformed

    private void itemMenuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuSairActionPerformed
        confirmaSaida dialog = new confirmaSaida(new javax.swing.JFrame(), true);
        dialog.setVisible(true);
    }//GEN-LAST:event_itemMenuSairActionPerformed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        confirmaSaida dialog = new confirmaSaida(new javax.swing.JFrame(), true);
        dialog.setVisible(true);
    }//GEN-LAST:event_btSairActionPerformed

    private void ItemMenuUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemMenuUsuarioActionPerformed
        try{
            //instaci da classe cadastro usuario
            configuracoesDeUsuario cu = new configuracoesDeUsuario();

            //se usuario for o gerente inabilita combo box usuario
            if(validaLogin.USUARIO.equals("Gerente")){

                cu.tipoUsuario.setEnabled(false);
            }

            //mostra a janela
            cu.setVisible(true);
        }

        catch(Exception e){
           JOptionPane.showMessageDialog(null, e);

        }

    }//GEN-LAST:event_ItemMenuUsuarioActionPerformed

    private void itemMenuSisserqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuSisserqActionPerformed
        sobreSisserq dialog = new sobreSisserq(new javax.swing.JFrame(), true);
        dialog.setVisible(true);
    }//GEN-LAST:event_itemMenuSisserqActionPerformed

    private void trocaUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trocaUsuarioActionPerformed
        //chama a confirmação de troca de usuário
        confirmaTrocaUsuario dialog = new confirmaTrocaUsuario(new javax.swing.JFrame(), true);
        dialog.setVisible(true);
        
        if(trocaUser == true){

            //fecha essa tela
            dispose();

            //chama tela de acesso
            telaAcesso ta = new telaAcesso(new javax.swing.JFrame(), true);
            ta.setVisible(true);
            
        }
        

        
       
    }//GEN-LAST:event_trocaUsuarioActionPerformed

    private void menuUtilCalcActionPerformed1(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuUtilCalcActionPerformed1
       try{
       Runtime cmd = Runtime.getRuntime();
       cmd.exec("calc.exe");
       }
       catch(Exception e){
       JOptionPane.showMessageDialog(null, e);
       }
    }//GEN-LAST:event_menuUtilCalcActionPerformed1

    private void menuUtilCalendActionPerformed1(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuUtilCalendActionPerformed1
        calendario dialog = new calendario(new javax.swing.JFrame(), false);
        dialog.setVisible(true);
    }//GEN-LAST:event_menuUtilCalendActionPerformed1

    private void btConfiguracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConfiguracaoActionPerformed
        //CHAMA A TELA DE CONFIGURAÇÕES
        configuracoes config = new configuracoes();
        config.setVisible(true);     
    }//GEN-LAST:event_btConfiguracaoActionPerformed

    private void menuUtilRemotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuUtilRemotActionPerformed
        try{
        Runtime c = Runtime.getRuntime();
        c.exec("C:\\Arquivos de programas\\RealVNC\\VNC4\\vncviewer.exe");
       }
       catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
       }

    }//GEN-LAST:event_menuUtilRemotActionPerformed

    private void relogioOnTime(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_relogioOnTime
 
        Data.le_data();
        Data.le_hora();

        mostraHora.setText("Hora atual:  "+Data.horaAtual);
        mostraData.setText(Data.dataAtualExtenso);

        Data.configuraTurno(Data.hora, Data.minuto);
        mostraTurno.setText(Data.mostraTurno());

//        if((Data.minuto%2) != 0)
//            lb_desenvolvidoPor.setForeground(new java.awt.Color(153, 153, 153));
//        else
//            lb_desenvolvidoPor.setForeground(new java.awt.Color(51, 51, 51));
    }//GEN-LAST:event_relogioOnTime

    private void btRelatBombonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRelatBombonaActionPerformed
        //CHAMA TEKA DE RALATÓRIO DE BOMBONA
        acompanhamentoPesagemBombona dialog = new acompanhamentoPesagemBombona();
        dialog.setVisible(true);
    }//GEN-LAST:event_btRelatBombonaActionPerformed

    private void btRelatInicineracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRelatInicineracaoActionPerformed
        //CHAMA TELA DE RALATÓRIO DE INCINERACAO
        acompanhamentoPesagemIncineracao dialog = new acompanhamentoPesagemIncineracao();
        dialog.setVisible(true); 
    }//GEN-LAST:event_btRelatInicineracaoActionPerformed

    private void menuRelatBombonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRelatBombonaActionPerformed
        //CHAMA TELA DE RALATÓRIO DE BOMBONA
        acompanhamentoPesagemBombona dialog = new acompanhamentoPesagemBombona();
        dialog.setVisible(true);
    }//GEN-LAST:event_menuRelatBombonaActionPerformed

    private void chamaSuspensosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chamaSuspensosActionPerformed
    CadastroCliente cc = new CadastroCliente();
    cc.btSuspensosDeterminados.setSelected(true);
    cc.rb_vencidos.setSelected(true);
    cc.rb_emDia.setVisible(true);
    cc.rb_vencidos.setVisible(true);
    auxiliar.validaCadCli.vizualizacaoSituacao("'SUSPENSO' and dia_retorno != '0000-00-00' and dia_retorno <= '"+validaLogin.DATAFORMAT+"'");
    cc.setVisible(true);
}//GEN-LAST:event_chamaSuspensosActionPerformed

    private void menuRelatIncineracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRelatIncineracaoActionPerformed
        //chama tela de suspens
        acompanhamentoPesagemIncineracao ai = new acompanhamentoPesagemIncineracao();
        ai.setVisible(true);
    }//GEN-LAST:event_menuRelatIncineracaoActionPerformed

    private void menuRelatUserBombonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRelatUserBombonaActionPerformed
        //chama tela de acompanhamento de pesagem de bombona por operador
        acompanhamentoPesagemUsuarioBombona au = new acompanhamentoPesagemUsuarioBombona();
        au.setVisible(true);
    }//GEN-LAST:event_menuRelatUserBombonaActionPerformed

    private void menuRelatUserIncineracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRelatUserIncineracaoActionPerformed
        //chama tela de acompnhamento de incineração por operador
        acompanhamentoPesagemUsuarioIncineracao aiu = new acompanhamentoPesagemUsuarioIncineracao();
        aiu.setVisible(true);
    }//GEN-LAST:event_menuRelatUserIncineracaoActionPerformed

    private void menuOpTocaUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuOpTocaUserActionPerformed
        //chama a confirmação de troca de usuário
        confirmaTrocaUsuario ct = new confirmaTrocaUsuario(new javax.swing.JFrame(), true);
        ct.setVisible(true);

        //se apertar o botao trocar de usuario a variável statica troca user recebe true e fecha a tela principal
        if(trocaUser == true){

            //fecha essa tela
            this.setVisible(false);

            //chama tela de acesso
            telaAcesso ta = new telaAcesso(new javax.swing.JFrame(), true);
            ta.setVisible(true);
        }
    }//GEN-LAST:event_menuOpTocaUserActionPerformed

    private void menuOpUserSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuOpUserSenhaActionPerformed
        //chama a telinha de troca de senha
        trocaSenha dialog = new trocaSenha(new javax.swing.JFrame(), true);
        dialog.setVisible(true);
    }//GEN-LAST:event_menuOpUserSenhaActionPerformed

    private void trocaSenhaOpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trocaSenhaOpActionPerformed
        trocaSenhaOp dialog = new trocaSenhaOp(new javax.swing.JFrame(), true);
        dialog.setVisible(true);
    }//GEN-LAST:event_trocaSenhaOpActionPerformed

    private void informaSituacaoGeralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_informaSituacaoGeralActionPerformed
        //chama tela de informações atuais da serquip
        informacoesAtuais dialog = new informacoesAtuais();
        dialog.setVisible(true);
    }//GEN-LAST:event_informaSituacaoGeralActionPerformed

    private void jMenuItem1ActionPerformed1(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed1
        //chama tela de informações atuais da serquip
        informacoesAtuais dialog = new informacoesAtuais();
        dialog.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed1

    private void lbAbertoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbAbertoMouseClicked

        if(aberto == true){
            
            lbAberto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fechado.png"))); // NOI18N
            aberto = false;

            bloqueiaTela.start();

            lb_bloqueadoEm.setVisible(true);
            lb_contador.setVisible(true);
            lb_seg.setVisible(true);
            
        }
        else{
             lbAberto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/aberto.png"))); // NOI18N
             aberto = true;
             
             bloqueiaTela.stop();
             
             lb_contador.setForeground(new java.awt.Color(0, 0, 0));

             lb_contador.setText("5");

             lb_bloqueadoEm.setVisible(false);
             lb_contador.setVisible(false);
             lb_seg.setVisible(false);
        }
    }//GEN-LAST:event_lbAbertoMouseClicked

    private void bloqueiaTelaOnTime(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bloqueiaTelaOnTime
        contaTempoBloqueio = Integer.parseInt(lb_contador.getText().toString()) - 1;
        lb_contador.setText(String.valueOf(contaTempoBloqueio));

        if(contaTempoBloqueio <=3){

            lb_contador.setForeground(new java.awt.Color(255, 0, 0));
        }
        else
            lb_contador.setForeground(new java.awt.Color(0, 0, 0));


        if(contaTempoBloqueio == 0){

            lb_bloqueadoEm.setVisible(false);
            lb_contador.setVisible(false);
            lb_seg.setVisible(false);

            parcialmenteBloqueado dialog = new parcialmenteBloqueado(new javax.swing.JFrame(), true);
            dialog.setVisible(true);
            
            bloqueiaTela.stop();

        }

    }//GEN-LAST:event_bloqueiaTelaOnTime

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        new ajuda().setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void informaSituacaoGeral1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_informaSituacaoGeral1ActionPerformed

        if(validaLogin.USUARIO.equals("Operador")){
              ajudaOP aj = new ajudaOP();
              aj.setVisible(true);
//            aj.geraltext.setText("<Não disponível para operador>");
//            aj.acompanhamentoBOText.setText("<Não disponível para operador>");
//            aj.acompanhamentoIOText.setText("<Não disponível para operador>");
//            aj.acompanhamentoIRText.setText("<Não disponível para operador>");
//            aj.acompanhamentoPBText.setText("<Não disponível para operador>");
//            aj.controleCliText.setText("<Não disponível para operador>");
//            aj.controleOPText.setText("<Não disponível para operador>");
//            aj.emissaoRelatText.setText("<Não disponível para operador>");
        }
        else{
              ajuda aj = new ajuda();
              aj.setVisible(true);

        }

        
        
    }//GEN-LAST:event_informaSituacaoGeral1ActionPerformed

    private void painelTurnoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painelTurnoMouseEntered
        if(mostraTurno.getText().equals("Manha"))
            painelTurno.setToolTipText("Horário manhã: das 6:00 às 14:20");
        if(mostraTurno.getText().equals("Tarde"))
            painelTurno.setToolTipText("Horário tarde: das 14:21 às 22:40");
        if(mostraTurno.getText().equals("Noite"))
            painelTurno.setToolTipText("Horário noite: das 22:41 às 5:59");
    }//GEN-LAST:event_painelTurnoMouseEntered

    private void menuLogUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLogUserActionPerformed
        new logUsuario().setVisible(true);
    }//GEN-LAST:event_menuLogUserActionPerformed

    private void chamaSuspensos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chamaSuspensos1ActionPerformed
        ativaExpirados();
    }//GEN-LAST:event_chamaSuspensos1ActionPerformed

    private void chamaSuspensos2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chamaSuspensos2ActionPerformed
        new relacaoSuspensosVencidos();
    }//GEN-LAST:event_chamaSuspensos2ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new telaPrincipal().setVisible(true);
                
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JMenuItem ItemMenuUsuario;
    public javax.swing.JMenuBar barraMenuPrincipal;
    protected static org.netbeans.examples.lib.timerbean.Timer bloqueiaTela;
    public javax.swing.JButton btBombona;
    public javax.swing.JButton btCliente;
    public javax.swing.JButton btConfiguracao;
    public javax.swing.JButton btIncinera;
    public javax.swing.JButton btRelatBombona;
    public javax.swing.JButton btRelatInicineracao;
    public javax.swing.JButton btSair;
    public javax.swing.JButton btUsuario;
    protected static javax.swing.JButton chamaSuspensos;
    protected static javax.swing.JButton chamaSuspensos1;
    protected static javax.swing.JButton chamaSuspensos2;
    protected static javax.swing.JLabel ci;
    public javax.swing.JButton informaSituacaoGeral;
    public javax.swing.JButton informaSituacaoGeral1;
    public javax.swing.JMenuItem itemMenuBombona;
    protected javax.swing.JMenuItem itemMenuCliente;
    public javax.swing.JMenuItem itemMenuIncinerar;
    protected javax.swing.JMenuItem itemMenuSair;
    protected javax.swing.JMenuItem itemMenuSisserq;
    protected static javax.swing.JLabel jLabel2;
    protected static javax.swing.JLabel jLabel7;
    protected static javax.swing.JMenuItem jMenuItem1;
    protected static javax.swing.JMenuItem jMenuItem2;
    protected static javax.swing.JPanel jPanel1;
    protected static javax.swing.JPanel jPanel2;
    protected static javax.swing.JPanel jPanel3;
    protected static javax.swing.JPanel jPanel4;
    protected static javax.swing.JPanel jPanel5;
    protected static javax.swing.JPanel jPanel6;
    protected static javax.swing.JSeparator jSeparator2;
    protected static javax.swing.JSeparator jSeparator3;
    public static javax.swing.JLabel lbAberto;
    public static javax.swing.JLabel lbSuspeso;
    public static javax.swing.JLabel lbUsuario;
    protected static javax.swing.JLabel lb_bloqueadoEm;
    protected static javax.swing.JLabel lb_contador;
    protected static javax.swing.JLabel lb_desenvolvidoPor;
    protected static javax.swing.JLabel lb_seg;
    public static javax.swing.JMenuItem menuLogUser;
    protected static javax.swing.JMenuItem menuOpTocaUser;
    protected static javax.swing.JMenu menuOpUser;
    protected static javax.swing.JMenuItem menuOpUserSenha;
    public javax.swing.JMenu menuOpcoes;
    protected static javax.swing.JMenuItem menuRelatBombona;
    protected static javax.swing.JMenuItem menuRelatIncineracao;
    protected static javax.swing.JMenuItem menuRelatUserBombona;
    protected static javax.swing.JMenuItem menuRelatUserIncineracao;
    public static javax.swing.JMenu menuRelatorio;
    public javax.swing.JMenu menuSistema;
    protected javax.swing.JMenuItem menuUtilCalc;
    protected static javax.swing.JMenuItem menuUtilCalend;
    protected static javax.swing.JMenuItem menuUtilRemot;
    public javax.swing.JMenu menuUtilitarios;
    protected static javax.swing.JLabel mostraData;
    protected static javax.swing.JLabel mostraHora;
    protected static javax.swing.JLabel mostraLogin;
    protected static javax.swing.JLabel mostraTurno;
    public javax.swing.JMenu munuSobre;
    protected static javax.swing.JLabel nomeHost;
    protected static javax.swing.JPanel painelPrincipal;
    public static javax.swing.JPanel painelSuspensao;
    public javax.swing.JPanel painelTurno;
    protected static org.netbeans.examples.lib.timerbean.Timer relogio;
    public javax.swing.JButton trocaSenhaOp;
    public javax.swing.JButton trocaUsuario;
    // End of variables declaration//GEN-END:variables

        //ver se tem algum contrato com a data de retorno expirada
        public static void verificaExpirados(){


            try{

            String sql = "select count(contrato_cli) as 'total expirados' from cliente where situacao = 'SUSPENSO' and (dia_retorno <= '"+validaLogin.DATAFORMAT+"') and (dia_retorno != '0000-00-00')";
            
            con_telaPrincipal.executeSQL(sql);
            con_telaPrincipal.resultset.first();
            
            qtdSuspensosExpirados = con_telaPrincipal.resultset.getInt("total expirados");

            if(qtdSuspensosExpirados > 0){

                painelSuspensao.setVisible(true);
                lbSuspeso.setText(qtdSuspensosExpirados+" cliente(s)");

            }
            if(qtdSuspensosExpirados == 0 )
                painelSuspensao.setVisible(false);


            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null, "Erro ao atualizar clientes com datas de coleta/suspensão vencidas\nErro: "+e);
                con_telaPrincipal.desconecta();
            }



}//fimn verifica suspensos

public static void ativaExpirados(){


            int op = JOptionPane.showConfirmDialog(null, "Sera(ão) ativado(s) "+qtdSuspensosExpirados+" cliente(s)\n\nDeseja continuar?", "Confirmação de ativação", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);

            if(op == 0){
                    String sql = "UPDATE cliente SET situacao = 'ATIVO'," +
                            " dia_cansus = '0000-00-00'," +
                            " dia_retorno = '0000-00-00', " +
                            " motivo = ''" +
                            " where situacao = 'SUSPENSO' and (dia_retorno <= '"+validaLogin.DATAFORMAT+"') and (dia_retorno != '0000-00-00')";
                    try{

                        int ativado = con_telaPrincipal.statement.executeUpdate(sql);

                        if(ativado >= 1){

                                JOptionPane.showMessageDialog(null, "Cliente(s) ativado(s) com sucesso!");
                                verificaExpirados();
                                

                        }

                    }
                    catch(Exception e){
                        JOptionPane.showMessageDialog(null, "Erro ao tentar ativar clientes com datas de suspensão vencida\nErro: "+e);
                        con_telaPrincipal.desconecta();
                    }
            }
            else
                return;

}
}
