/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * acompanhamentoPesagemIncineracao.java
 *
 * Created on 11/02/2010, 05:19:45
 */

package RelatorioForm;
import auxiliar.acompanhamentoPesagemIncineracaoAux;
import javax.swing.*;
import javax.swing.text.MaskFormatter;
import RelatorioJava.acompanhamentoInci;
/**
 *
 * @author ayrton monier
 */
public class acompanhamentoPesagemIncineracao extends javax.swing.JFrame {

    MaskFormatter formData;

    /** Creates new form acompanhamentoPesagemIncineracao */
    public acompanhamentoPesagemIncineracao() {
        initComponents();

        this.setExtendedState(MAXIMIZED_BOTH);
        acompanhamentoPesagemIncineracaoAux.iniciaComponentes();

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tempoReal = new org.netbeans.examples.lib.timerbean.Timer();
        grupoOpcoes = new javax.swing.ButtonGroup();
        grupoOrdenacao = new javax.swing.ButtonGroup();
        btNovoRelatorio = new javax.swing.JButton();
        btSair = new javax.swing.JButton();
        jPanel16 = new javax.swing.JPanel();
        painelM1 = new javax.swing.JPanel();
        jLabel38 = new javax.swing.JLabel();
        totalMaquina1 = new javax.swing.JTextField();
        jLabel89 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        totalBiologico1 = new javax.swing.JTextField();
        jLabel93 = new javax.swing.JLabel();
        lbInd1 = new javax.swing.JLabel();
        totalIndustrial1 = new javax.swing.JTextField();
        lbKg1 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        totalCarrinhos1 = new javax.swing.JTextField();
        jLabel101 = new javax.swing.JLabel();
        lbInd4 = new javax.swing.JLabel();
        qtdCarBioM1 = new javax.swing.JTextField();
        lbKg4 = new javax.swing.JLabel();
        lbInd5 = new javax.swing.JLabel();
        qtdCarIndM1 = new javax.swing.JTextField();
        lbKg5 = new javax.swing.JLabel();
        painelM2 = new javax.swing.JPanel();
        jLabel39 = new javax.swing.JLabel();
        totalMaquina2 = new javax.swing.JTextField();
        jLabel90 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        totalBiologico2 = new javax.swing.JTextField();
        jLabel94 = new javax.swing.JLabel();
        lbInd2 = new javax.swing.JLabel();
        totalIndustrial2 = new javax.swing.JTextField();
        lbKg2 = new javax.swing.JLabel();
        totalCarrinhos2 = new javax.swing.JTextField();
        jLabel51 = new javax.swing.JLabel();
        jLabel102 = new javax.swing.JLabel();
        lbInd6 = new javax.swing.JLabel();
        qtdCarBioM2 = new javax.swing.JTextField();
        lbKg6 = new javax.swing.JLabel();
        lbInd7 = new javax.swing.JLabel();
        qtdCarIndM2 = new javax.swing.JTextField();
        lbKg7 = new javax.swing.JLabel();
        painelM3 = new javax.swing.JPanel();
        jLabel40 = new javax.swing.JLabel();
        totalMaquina3 = new javax.swing.JTextField();
        jLabel91 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        totalBiologico3 = new javax.swing.JTextField();
        jLabel95 = new javax.swing.JLabel();
        lbInd3 = new javax.swing.JLabel();
        totalIndustrial3 = new javax.swing.JTextField();
        lbKg3 = new javax.swing.JLabel();
        totalCarrinhos3 = new javax.swing.JTextField();
        jLabel52 = new javax.swing.JLabel();
        jLabel103 = new javax.swing.JLabel();
        lbInd8 = new javax.swing.JLabel();
        qtdCarIndM3 = new javax.swing.JTextField();
        lbKg8 = new javax.swing.JLabel();
        lbInd9 = new javax.swing.JLabel();
        lbKg9 = new javax.swing.JLabel();
        qtdCarBioM3 = new javax.swing.JTextField();
        painelTotal = new javax.swing.JPanel();
        jLabel47 = new javax.swing.JLabel();
        totalMaquinas = new javax.swing.JTextField();
        jLabel92 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        totalBiologico = new javax.swing.JTextField();
        jLabel99 = new javax.swing.JLabel();
        lbInd = new javax.swing.JLabel();
        totalIndustrial = new javax.swing.JTextField();
        lbKg = new javax.swing.JLabel();
        totalCarrinhos = new javax.swing.JTextField();
        jLabel53 = new javax.swing.JLabel();
        jLabel104 = new javax.swing.JLabel();
        lbInd10 = new javax.swing.JLabel();
        qtdCarIndMs = new javax.swing.JTextField();
        lbKg10 = new javax.swing.JLabel();
        lbKg11 = new javax.swing.JLabel();
        qtdCarBioMs = new javax.swing.JTextField();
        lbInd11 = new javax.swing.JLabel();
        btImprimir = new javax.swing.JButton();
        btConfirmaBusca = new javax.swing.JButton();
        btAtualiza = new javax.swing.JButton();
        scrollTabInci = new javax.swing.JScrollPane();
        tabelaInci = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        ordenaCodigo = new javax.swing.JRadioButton();
        acompanhaDiaPeriodo4 = new javax.swing.JRadioButton();
        acompanhaDiaPeriodo5 = new javax.swing.JRadioButton();
        acompanhaDiaPeriodo6 = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        pesagemHoje = new javax.swing.JRadioButton();
        acompanhaDiaPeriodo = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        try{
            formData = new MaskFormatter("##-##-####");
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Não foi possível inserir a máscara no campo, erro :"+e);
        }
        periodoDe = new JFormattedTextField(formData);
        try{
            formData = new MaskFormatter("##-##-####");
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Não foi possível inserir a máscara no campo, erro :"+e);
        }
        periodoA = new JFormattedTextField(formData);
        a = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        maquina = new javax.swing.JComboBox();
        tipoResiduo = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        turno = new javax.swing.JComboBox();

        tempoReal.addTimerListener(new org.netbeans.examples.lib.timerbean.TimerListener() {
            public void onTime(java.awt.event.ActionEvent evt) {
                tempoRealOnTime(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Acompanhamento de pesagem de resíduos - Sistema Serquip 1.0");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        btNovoRelatorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/novo_relatorio.png"))); // NOI18N
        btNovoRelatorio.setToolTipText("Nova consulta");
        btNovoRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNovoRelatorioActionPerformed(evt);
            }
        });

        btSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/sair.png"))); // NOI18N
        btSair.setToolTipText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        jPanel16.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("Campos de retorno de valores")));
        jPanel16.setToolTipText("");

        painelM1.setBorder(javax.swing.BorderFactory.createTitledBorder("Máquina 1"));

        jLabel38.setText("Total Inc. Maq. 1:");

        totalMaquina1.setEditable(false);
        totalMaquina1.setForeground(new java.awt.Color(255, 0, 0));

        jLabel89.setText("Kg");

        jLabel41.setText("Resíduo Biológico:");

        totalBiologico1.setEditable(false);
        totalBiologico1.setForeground(new java.awt.Color(255, 0, 0));

        jLabel93.setText("Kg");

        lbInd1.setText("Resíduo Industrial:");

        totalIndustrial1.setEditable(false);
        totalIndustrial1.setForeground(new java.awt.Color(255, 0, 0));

        lbKg1.setText("Kg");

        jLabel50.setText("Qtd. de carrinhos:");

        totalCarrinhos1.setEditable(false);
        totalCarrinhos1.setForeground(new java.awt.Color(255, 0, 0));

        jLabel101.setText("Und.");

        lbInd4.setText("Qtd. car. res. Bio.:");

        qtdCarBioM1.setEditable(false);
        qtdCarBioM1.setForeground(new java.awt.Color(255, 0, 0));

        lbKg4.setText("Kg");

        lbInd5.setText("Qtd. car. res. ind.:");

        qtdCarIndM1.setEditable(false);
        qtdCarIndM1.setForeground(new java.awt.Color(255, 0, 0));

        lbKg5.setText("Kg");

        javax.swing.GroupLayout painelM1Layout = new javax.swing.GroupLayout(painelM1);
        painelM1.setLayout(painelM1Layout);
        painelM1Layout.setHorizontalGroup(
            painelM1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelM1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelM1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel38)
                    .addComponent(lbInd1)
                    .addComponent(jLabel41)
                    .addComponent(jLabel50)
                    .addComponent(lbInd4)
                    .addComponent(lbInd5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelM1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(totalCarrinhos1)
                    .addComponent(qtdCarBioM1)
                    .addComponent(qtdCarIndM1)
                    .addComponent(totalIndustrial1)
                    .addComponent(totalBiologico1)
                    .addComponent(totalMaquina1, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelM1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel93)
                    .addComponent(jLabel89)
                    .addComponent(lbKg1)
                    .addComponent(lbKg5)
                    .addComponent(lbKg4)
                    .addComponent(jLabel101, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        painelM1Layout.setVerticalGroup(
            painelM1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelM1Layout.createSequentialGroup()
                .addGroup(painelM1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalMaquina1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel89))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelM1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel41)
                    .addComponent(totalBiologico1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel93))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelM1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbInd1)
                    .addComponent(totalIndustrial1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbKg1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelM1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbInd5)
                    .addComponent(qtdCarIndM1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbKg5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelM1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbInd4)
                    .addComponent(qtdCarBioM1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbKg4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelM1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel50)
                    .addComponent(totalCarrinhos1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel101))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        painelM2.setBorder(javax.swing.BorderFactory.createTitledBorder("Máquina 2"));

        jLabel39.setText("Total Inc. Maq. 2:");

        totalMaquina2.setEditable(false);
        totalMaquina2.setForeground(new java.awt.Color(255, 0, 0));

        jLabel90.setText("Kg");

        jLabel43.setText("Resíduo Biológico:");

        totalBiologico2.setEditable(false);
        totalBiologico2.setForeground(new java.awt.Color(255, 0, 0));

        jLabel94.setText("Kg");

        lbInd2.setText("Resíduo Industrial:");

        totalIndustrial2.setEditable(false);
        totalIndustrial2.setForeground(new java.awt.Color(255, 0, 0));

        lbKg2.setText("Kg");

        totalCarrinhos2.setEditable(false);
        totalCarrinhos2.setForeground(new java.awt.Color(255, 0, 0));

        jLabel51.setText("Qtd. de carrinhos:");

        jLabel102.setText("Und.");

        lbInd6.setText("Qtd. car. res. Bio.:");

        qtdCarBioM2.setEditable(false);
        qtdCarBioM2.setForeground(new java.awt.Color(255, 0, 0));

        lbKg6.setText("Kg");

        lbInd7.setText("Qtd. car. res. ind.:");

        qtdCarIndM2.setEditable(false);
        qtdCarIndM2.setForeground(new java.awt.Color(255, 0, 0));

        lbKg7.setText("Kg");

        javax.swing.GroupLayout painelM2Layout = new javax.swing.GroupLayout(painelM2);
        painelM2.setLayout(painelM2Layout);
        painelM2Layout.setHorizontalGroup(
            painelM2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelM2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(painelM2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel39)
                    .addComponent(lbInd2)
                    .addComponent(jLabel43)
                    .addComponent(jLabel51)
                    .addComponent(lbInd6)
                    .addComponent(lbInd7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelM2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(totalIndustrial2)
                    .addComponent(totalBiologico2)
                    .addComponent(totalCarrinhos2, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                    .addComponent(totalMaquina2)
                    .addComponent(qtdCarBioM2)
                    .addComponent(qtdCarIndM2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelM2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelM2Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(painelM2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel90)
                            .addComponent(jLabel94)))
                    .addGroup(painelM2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(painelM2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbKg2)
                            .addComponent(jLabel102)
                            .addComponent(lbKg6)
                            .addComponent(lbKg7)))))
        );
        painelM2Layout.setVerticalGroup(
            painelM2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelM2Layout.createSequentialGroup()
                .addGroup(painelM2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalMaquina2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel90))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelM2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel43)
                    .addComponent(totalBiologico2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel94))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelM2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbInd2)
                    .addComponent(totalIndustrial2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbKg2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelM2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbInd7)
                    .addComponent(qtdCarIndM2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbKg7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelM2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbInd6)
                    .addComponent(qtdCarBioM2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbKg6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelM2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel51)
                    .addComponent(totalCarrinhos2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel102))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        painelM3.setBorder(javax.swing.BorderFactory.createTitledBorder("Máquina 3"));

        jLabel40.setText("Total Inc. Maq. 3:");

        totalMaquina3.setEditable(false);
        totalMaquina3.setForeground(new java.awt.Color(255, 0, 0));

        jLabel91.setText("Kg");

        jLabel45.setText("Resíduo Biológico:");

        totalBiologico3.setEditable(false);
        totalBiologico3.setForeground(new java.awt.Color(255, 0, 0));

        jLabel95.setText("Kg");

        lbInd3.setText("Resíduo Industrial:");

        totalIndustrial3.setEditable(false);
        totalIndustrial3.setForeground(new java.awt.Color(255, 0, 0));

        lbKg3.setText("Kg");

        totalCarrinhos3.setEditable(false);
        totalCarrinhos3.setForeground(new java.awt.Color(255, 0, 0));

        jLabel52.setText("Qtd. de carrinhos:");

        jLabel103.setText("Und.");

        lbInd8.setText("Qtd. car. res. ind.:");

        qtdCarIndM3.setEditable(false);
        qtdCarIndM3.setForeground(new java.awt.Color(255, 0, 0));

        lbKg8.setText("Kg");

        lbInd9.setText("Qtd. car. res. Bio.:");

        lbKg9.setText("Kg");

        qtdCarBioM3.setEditable(false);
        qtdCarBioM3.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout painelM3Layout = new javax.swing.GroupLayout(painelM3);
        painelM3.setLayout(painelM3Layout);
        painelM3Layout.setHorizontalGroup(
            painelM3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelM3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(painelM3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel52)
                    .addComponent(lbInd9)
                    .addComponent(lbInd8)
                    .addComponent(lbInd3)
                    .addComponent(jLabel45)
                    .addComponent(jLabel40))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelM3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(totalCarrinhos3)
                    .addComponent(qtdCarBioM3)
                    .addComponent(qtdCarIndM3)
                    .addComponent(totalIndustrial3)
                    .addComponent(totalBiologico3)
                    .addComponent(totalMaquina3, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelM3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel95)
                    .addComponent(jLabel91)
                    .addComponent(lbKg3)
                    .addComponent(lbKg8)
                    .addComponent(lbKg9)
                    .addComponent(jLabel103)))
        );
        painelM3Layout.setVerticalGroup(
            painelM3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelM3Layout.createSequentialGroup()
                .addGroup(painelM3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalMaquina3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel91))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelM3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalBiologico3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel45)
                    .addComponent(jLabel95))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelM3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalIndustrial3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbInd3)
                    .addComponent(lbKg3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelM3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(qtdCarIndM3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbInd8)
                    .addComponent(lbKg8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelM3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(qtdCarBioM3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbInd9)
                    .addComponent(lbKg9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelM3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalCarrinhos3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel52)
                    .addComponent(jLabel103))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        painelTotal.setBorder(javax.swing.BorderFactory.createTitledBorder("Total das máquinas"));

        jLabel47.setText("Total Inc. Maqns:");

        totalMaquinas.setEditable(false);
        totalMaquinas.setForeground(new java.awt.Color(255, 0, 0));

        jLabel92.setText("Kg");

        jLabel48.setText("Resíduo Biológico:");

        totalBiologico.setEditable(false);
        totalBiologico.setForeground(new java.awt.Color(255, 0, 0));

        jLabel99.setText("Kg");

        lbInd.setText("Resíduo Industrial:");

        totalIndustrial.setEditable(false);
        totalIndustrial.setForeground(new java.awt.Color(255, 0, 0));

        lbKg.setText("Kg");

        totalCarrinhos.setEditable(false);
        totalCarrinhos.setForeground(new java.awt.Color(255, 0, 0));

        jLabel53.setText("Qtd. de carrinhos:");

        jLabel104.setText("Und.");

        lbInd10.setText("Qtd. car. res. ind.:");

        qtdCarIndMs.setEditable(false);
        qtdCarIndMs.setForeground(new java.awt.Color(255, 0, 0));

        lbKg10.setText("Kg");

        lbKg11.setText("Kg");

        qtdCarBioMs.setEditable(false);
        qtdCarBioMs.setForeground(new java.awt.Color(255, 0, 0));

        lbInd11.setText("Qtd. car. res. Bio.:");

        javax.swing.GroupLayout painelTotalLayout = new javax.swing.GroupLayout(painelTotal);
        painelTotal.setLayout(painelTotalLayout);
        painelTotalLayout.setHorizontalGroup(
            painelTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelTotalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(painelTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel47)
                    .addComponent(lbInd)
                    .addComponent(jLabel48)
                    .addComponent(jLabel53)
                    .addComponent(lbInd10)
                    .addComponent(lbInd11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(totalCarrinhos)
                    .addComponent(qtdCarBioMs)
                    .addComponent(qtdCarIndMs)
                    .addComponent(totalIndustrial)
                    .addComponent(totalBiologico)
                    .addComponent(totalMaquinas, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel99)
                    .addComponent(jLabel92)
                    .addComponent(lbKg)
                    .addComponent(lbKg10)
                    .addComponent(lbKg11)
                    .addComponent(jLabel104)))
        );
        painelTotalLayout.setVerticalGroup(
            painelTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelTotalLayout.createSequentialGroup()
                .addGroup(painelTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel47, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalMaquinas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel92))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel48)
                    .addComponent(totalBiologico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel99))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbInd)
                    .addComponent(totalIndustrial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbKg))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbInd10)
                    .addComponent(qtdCarIndMs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbKg10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbInd11)
                    .addComponent(qtdCarBioMs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbKg11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel53)
                    .addComponent(totalCarrinhos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel104))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addComponent(painelM1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelM2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelM3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(painelM1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(painelM2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(painelM3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(painelTotal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        btImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/imprimir.png"))); // NOI18N
        btImprimir.setToolTipText("Imprimir ficha do cliente");
        btImprimir.setEnabled(false);
        btImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btImprimirActionPerformed(evt);
            }
        });

        btConfirmaBusca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ok.png"))); // NOI18N
        btConfirmaBusca.setToolTipText("Confirmar consulta");
        btConfirmaBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConfirmaBuscaActionPerformed(evt);
            }
        });

        btAtualiza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/atualiza.png"))); // NOI18N
        btAtualiza.setToolTipText("Atualizar consulta");
        btAtualiza.setEnabled(false);
        btAtualiza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAtualizaActionPerformed(evt);
            }
        });

        tabelaInci.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código do carrinho", "Peso do carrinho", "Tipo de Resíduo", "Máquina", "Data", "Turno", "Hora", "Operador"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrollTabInci.setViewportView(tabelaInci);

        jPanel7.setBackground(new java.awt.Color(204, 204, 204));
        jPanel7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), "Opções de ordenação de consultas"));

        ordenaCodigo.setBackground(new java.awt.Color(204, 204, 204));
        grupoOrdenacao.add(ordenaCodigo);
        ordenaCodigo.setSelected(true);
        ordenaCodigo.setText("Código");
        ordenaCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ordenaCodigoActionPerformed(evt);
            }
        });

        acompanhaDiaPeriodo4.setBackground(new java.awt.Color(204, 204, 204));
        grupoOrdenacao.add(acompanhaDiaPeriodo4);
        acompanhaDiaPeriodo4.setText("Tipo resíduo");
        acompanhaDiaPeriodo4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acompanhaDiaPeriodo4ActionPerformed(evt);
            }
        });

        acompanhaDiaPeriodo5.setBackground(new java.awt.Color(204, 204, 204));
        grupoOrdenacao.add(acompanhaDiaPeriodo5);
        acompanhaDiaPeriodo5.setText("Data");
        acompanhaDiaPeriodo5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acompanhaDiaPeriodo5ActionPerformed(evt);
            }
        });

        acompanhaDiaPeriodo6.setBackground(new java.awt.Color(204, 204, 204));
        grupoOrdenacao.add(acompanhaDiaPeriodo6);
        acompanhaDiaPeriodo6.setText("Turno");
        acompanhaDiaPeriodo6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acompanhaDiaPeriodo6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ordenaCodigo)
                    .addComponent(acompanhaDiaPeriodo5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(acompanhaDiaPeriodo4)
                    .addComponent(acompanhaDiaPeriodo6))
                .addGap(34, 34, 34))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ordenaCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(acompanhaDiaPeriodo4, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(acompanhaDiaPeriodo5, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(acompanhaDiaPeriodo6, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), "Opções de acompanhamento de incineração"));

        pesagemHoje.setBackground(new java.awt.Color(204, 204, 204));
        grupoOpcoes.add(pesagemHoje);
        pesagemHoje.setText("Consultar incineração de hoje");
        pesagemHoje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesagemHojeActionPerformed(evt);
            }
        });

        acompanhaDiaPeriodo.setBackground(new java.awt.Color(204, 204, 204));
        grupoOpcoes.add(acompanhaDiaPeriodo);
        acompanhaDiaPeriodo.setSelected(true);
        acompanhaDiaPeriodo.setText("Consultar dia ou período de incineração");
        acompanhaDiaPeriodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acompanhaDiaPeriodoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(acompanhaDiaPeriodo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addComponent(pesagemHoje)
                .addGap(52, 52, 52))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(acompanhaDiaPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pesagemHoje, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), "Período"));

        periodoDe.setToolTipText("Digite a data inicial da pesquisa");
        periodoDe.setFont(new java.awt.Font("Tahoma", 1, 14));
        periodoDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                periodoDeActionPerformed(evt);
            }
        });

        periodoA.setToolTipText("Se habilitado digite a data final da consulta");
        periodoA.setFont(new java.awt.Font("Tahoma", 1, 14));

        a.setText("a:");
        a.setToolTipText("Adiciona a data final da consulta");
        a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(periodoDe, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(a)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(periodoA, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(periodoA, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a)
                    .addComponent(periodoDe, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), "Opções do filtro de consulta"));

        jLabel7.setText("Tipo de resíduo:");

        maquina.setFont(new java.awt.Font("Tahoma", 1, 12));
        maquina.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Todas", "Maquina 1", "Maquina 2", "Maquina 3" }));
        maquina.setToolTipText("Escolha uma das capacidades ou todas");
        maquina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maquinaActionPerformed(evt);
            }
        });

        tipoResiduo.setFont(new java.awt.Font("Tahoma", 1, 12));
        tipoResiduo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Todos", "Biologico", "Industrial" }));
        tipoResiduo.setToolTipText("Escolha bombonas de contrato ou extra");
        tipoResiduo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoResiduoActionPerformed(evt);
            }
        });

        jLabel6.setText("Máquina:");

        jLabel5.setText("Turno:");

        turno.setFont(new java.awt.Font("Tahoma", 1, 12));
        turno.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Dia completo", "Manha", "Tarde", "Noite" }));
        turno.setToolTipText("Escolha um dos turnos ou o dia completo");
        turno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                turnoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6))
                .addGap(4, 4, 4)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(tipoResiduo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(maquina, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(turno, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(turno, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(maquina, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tipoResiduo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 348, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btConfirmaBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btNovoRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btAtualiza, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btSair, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(scrollTabInci, javax.swing.GroupLayout.DEFAULT_SIZE, 1162, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btAtualiza)
                    .addComponent(btNovoRelatorio)
                    .addComponent(btImprimir)
                    .addComponent(btSair)
                    .addComponent(btConfirmaBusca, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollTabInci, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        java.awt.Dimension dialogSize = getSize();
        setLocation((screenSize.width-dialogSize.width)/2,(screenSize.height-dialogSize.height)/2);
    }// </editor-fold>//GEN-END:initComponents

    private void btNovoRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNovoRelatorioActionPerformed
        acompanhamentoPesagemIncineracaoAux.novoRelatorio();
}//GEN-LAST:event_btNovoRelatorioActionPerformed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        int opcao_escolhida = JOptionPane.showConfirmDialog(null, "DESEJA REALMENTE SAIR?", "Sair", JOptionPane.YES_NO_OPTION);

        if(opcao_escolhida == JOptionPane.YES_OPTION){
            dispose();
            acompanhamentoPesagemIncineracaoAux.desconecta();
        } else
            return;
}//GEN-LAST:event_btSairActionPerformed

    private void btImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btImprimirActionPerformed
        new acompanhamentoInci();
}//GEN-LAST:event_btImprimirActionPerformed

    private void btConfirmaBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConfirmaBuscaActionPerformed
        acompanhamentoPesagemIncineracaoAux.validaCampos();
        acompanhamentoPesagemIncineracaoAux.configuraParaPesquisa();
}//GEN-LAST:event_btConfirmaBuscaActionPerformed

    private void btAtualizaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAtualizaActionPerformed

        //atualiza pesquisa
        acompanhamentoPesagemIncineracaoAux.validaCampos();
        acompanhamentoPesagemIncineracaoAux.configuraParaPesquisa();
        acompanhamentoPesagemIncineracaoAux.atualizaPesquisa();
}//GEN-LAST:event_btAtualizaActionPerformed

    private void ordenaCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ordenaCodigoActionPerformed
        acompanhamentoPesagemIncineracaoAux.ordenacao = "num_seq_incineracao";
}//GEN-LAST:event_ordenaCodigoActionPerformed

    private void acompanhaDiaPeriodo4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acompanhaDiaPeriodo4ActionPerformed
        acompanhamentoPesagemIncineracaoAux.ordenacao = "tipo_residuo";
}//GEN-LAST:event_acompanhaDiaPeriodo4ActionPerformed

    private void acompanhaDiaPeriodo5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acompanhaDiaPeriodo5ActionPerformed
        acompanhamentoPesagemIncineracaoAux.ordenacao = "data_incineracao";
}//GEN-LAST:event_acompanhaDiaPeriodo5ActionPerformed

    private void acompanhaDiaPeriodo6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acompanhaDiaPeriodo6ActionPerformed
        acompanhamentoPesagemIncineracaoAux.ordenacao = "turno_incineracao";
}//GEN-LAST:event_acompanhaDiaPeriodo6ActionPerformed

    private void pesagemHojeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesagemHojeActionPerformed
        acompanhamentoPesagemIncineracaoAux.limpaCamposAcompanhamento();
        acompanhamentoPesagemIncineracaoAux.pesadasHoje();
}//GEN-LAST:event_pesagemHojeActionPerformed

    private void acompanhaDiaPeriodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acompanhaDiaPeriodoActionPerformed
        acompanhamentoPesagemIncineracaoAux.limpaCamposAcompanhamento();
        acompanhamentoPesagemIncineracaoAux.acompanhaDiaPeriodo();
}//GEN-LAST:event_acompanhaDiaPeriodoActionPerformed

    private void periodoDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_periodoDeActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_periodoDeActionPerformed

    private void aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aActionPerformed
        if(a.isSelected()){
            periodoA.setEditable(false);
            periodoA.setText("");
            a.setSelected(false);
        } else{
            periodoA.setEditable(true);
            periodoA.requestFocus();
            a.setSelected(true);
        }
}//GEN-LAST:event_aActionPerformed

    private void maquinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maquinaActionPerformed
        //se CAPACIDADE DA BOMBONA selecionado for 200 litros
        if(maquina.getSelectedItem().toString().equals("Maquina 1")){
            painelTotal.setVisible(false);
            painelM1.setVisible(true);
            painelM2.setVisible(false);
            painelM3.setVisible(false);
        }

        //se CAPACIDADE DA BOMBONA selecionado for 50 litros
        else if(maquina.getSelectedItem().toString().equals("Maquina 2")){
            painelTotal.setVisible(false);
            painelM1.setVisible(false);
            painelM2.setVisible(true);
            painelM3.setVisible(false);

        }

        //se CAPACIDADE DA BOMBONA selecionado for 20 litros
        else if(maquina.getSelectedItem().toString().equals("Maquina 3")){
            painelTotal.setVisible(false);
            painelM1.setVisible(false);
            painelM2.setVisible(false);
            painelM3.setVisible(true);

        }

        //se CAPACIDADE DA BOMBONA selecionado for 200
        else{
            painelTotal.setVisible(true);
            painelM1.setVisible(true);
            painelM2.setVisible(true);
            painelM3.setVisible(true);
        }
}//GEN-LAST:event_maquinaActionPerformed

    private void tipoResiduoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoResiduoActionPerformed
        //        if(tipoResiduo.getSelectedItem().equals("Biologico")){
        //            totalIndustrial1.setBackground(new java.awt.Color(255, 0, 0));
        //            totalIndustrial2.setBackground(new java.awt.Color(255, 0, 0));
        //            totalIndustrial3.setBackground(new java.awt.Color(255, 0, 0));
        //            totalIndustrial.setBackground(new java.awt.Color(255, 0, 0));
        //
        //            totalBiologico1.setBackground(new java.awt.Color(255, 255, 255));
        //            totalBiologico2.setBackground(new java.awt.Color(255, 255, 255));
        //            totalBiologico3.setBackground(new java.awt.Color(255, 255, 255));
        //            totalBiologico.setBackground(new java.awt.Color(255, 255, 255));
        //
        //        }
        //        else if(tipoResiduo.getSelectedItem().equals("Industrial")){
        //            totalBiologico1.setBackground(new java.awt.Color(255, 0, 0));
        //            totalBiologico2.setBackground(new java.awt.Color(255, 0, 0));
        //            totalBiologico3.setBackground(new java.awt.Color(255, 0, 0));
        //            totalBiologico.setBackground(new java.awt.Color(255, 0, 0));
        //
        //            totalIndustrial1.setBackground(new java.awt.Color(255, 255, 255));
        //            totalIndustrial2.setBackground(new java.awt.Color(255, 255, 255));
        //            totalIndustrial3.setBackground(new java.awt.Color(255, 255, 255));
        //            totalIndustrial.setBackground(new java.awt.Color(255, 255, 255));
        //
        //        }
        //        else{
        //            totalBiologico1.setBackground(new java.awt.Color(255, 255, 255));
        //            totalBiologico2.setBackground(new java.awt.Color(255, 255, 255));
        //            totalBiologico3.setBackground(new java.awt.Color(255, 255, 255));
        //            totalBiologico.setBackground(new java.awt.Color(255, 255, 255));
        //
        //            totalIndustrial1.setBackground(new java.awt.Color(255, 255, 255));
        //            totalIndustrial2.setBackground(new java.awt.Color(255, 255, 255));
        //            totalIndustrial3.setBackground(new java.awt.Color(255, 255, 255));
        //            totalIndustrial.setBackground(new java.awt.Color(255, 255, 255));
        //        }
    }//GEN-LAST:event_tipoResiduoActionPerformed

    private void turnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_turnoActionPerformed

}//GEN-LAST:event_turnoActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        int opcao_escolhida = JOptionPane.showConfirmDialog(null, "DESEJA REALMENTE SAIR?", "Sair", JOptionPane.YES_NO_OPTION);

        if(opcao_escolhida == JOptionPane.YES_OPTION){
            dispose();
            acompanhamentoPesagemIncineracaoAux.desconecta();
        } else
            return;
    }//GEN-LAST:event_formWindowClosing

    private void tempoRealOnTime(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tempoRealOnTime
        acompanhamentoPesagemIncineracaoAux.atualizaPesquisa();
    }//GEN-LAST:event_tempoRealOnTime

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new acompanhamentoPesagemIncineracao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton a;
    public static javax.swing.JRadioButton acompanhaDiaPeriodo;
    public static javax.swing.JRadioButton acompanhaDiaPeriodo4;
    public static javax.swing.JRadioButton acompanhaDiaPeriodo5;
    public static javax.swing.JRadioButton acompanhaDiaPeriodo6;
    public static javax.swing.JButton btAtualiza;
    public static javax.swing.JButton btConfirmaBusca;
    public static javax.swing.JButton btImprimir;
    public static javax.swing.JButton btNovoRelatorio;
    public static javax.swing.JButton btSair;
    private javax.swing.ButtonGroup grupoOpcoes;
    private javax.swing.ButtonGroup grupoOrdenacao;
    private javax.swing.JLabel jLabel101;
    private javax.swing.JLabel jLabel102;
    private javax.swing.JLabel jLabel103;
    private javax.swing.JLabel jLabel104;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel89;
    private javax.swing.JLabel jLabel90;
    private javax.swing.JLabel jLabel91;
    private javax.swing.JLabel jLabel92;
    private javax.swing.JLabel jLabel93;
    private javax.swing.JLabel jLabel94;
    private javax.swing.JLabel jLabel95;
    private javax.swing.JLabel jLabel99;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel lbInd;
    private javax.swing.JLabel lbInd1;
    private javax.swing.JLabel lbInd10;
    private javax.swing.JLabel lbInd11;
    private javax.swing.JLabel lbInd2;
    private javax.swing.JLabel lbInd3;
    private javax.swing.JLabel lbInd4;
    private javax.swing.JLabel lbInd5;
    private javax.swing.JLabel lbInd6;
    private javax.swing.JLabel lbInd7;
    private javax.swing.JLabel lbInd8;
    private javax.swing.JLabel lbInd9;
    private javax.swing.JLabel lbKg;
    private javax.swing.JLabel lbKg1;
    private javax.swing.JLabel lbKg10;
    private javax.swing.JLabel lbKg11;
    private javax.swing.JLabel lbKg2;
    private javax.swing.JLabel lbKg3;
    private javax.swing.JLabel lbKg4;
    private javax.swing.JLabel lbKg5;
    private javax.swing.JLabel lbKg6;
    private javax.swing.JLabel lbKg7;
    private javax.swing.JLabel lbKg8;
    private javax.swing.JLabel lbKg9;
    public static javax.swing.JComboBox maquina;
    public static javax.swing.JRadioButton ordenaCodigo;
    public static javax.swing.JPanel painelM1;
    public static javax.swing.JPanel painelM2;
    public static javax.swing.JPanel painelM3;
    public static javax.swing.JPanel painelTotal;
    public static javax.swing.JFormattedTextField periodoA;
    public static javax.swing.JFormattedTextField periodoDe;
    public static javax.swing.JRadioButton pesagemHoje;
    public static javax.swing.JTextField qtdCarBioM1;
    public static javax.swing.JTextField qtdCarBioM2;
    public static javax.swing.JTextField qtdCarBioM3;
    public static javax.swing.JTextField qtdCarBioMs;
    public static javax.swing.JTextField qtdCarIndM1;
    public static javax.swing.JTextField qtdCarIndM2;
    public static javax.swing.JTextField qtdCarIndM3;
    public static javax.swing.JTextField qtdCarIndMs;
    private javax.swing.JScrollPane scrollTabInci;
    public static javax.swing.JTable tabelaInci;
    public static org.netbeans.examples.lib.timerbean.Timer tempoReal;
    public static javax.swing.JComboBox tipoResiduo;
    public static javax.swing.JTextField totalBiologico;
    public static javax.swing.JTextField totalBiologico1;
    public static javax.swing.JTextField totalBiologico2;
    public static javax.swing.JTextField totalBiologico3;
    public static javax.swing.JTextField totalCarrinhos;
    public static javax.swing.JTextField totalCarrinhos1;
    public static javax.swing.JTextField totalCarrinhos2;
    public static javax.swing.JTextField totalCarrinhos3;
    public static javax.swing.JTextField totalIndustrial;
    public static javax.swing.JTextField totalIndustrial1;
    public static javax.swing.JTextField totalIndustrial2;
    public static javax.swing.JTextField totalIndustrial3;
    public static javax.swing.JTextField totalMaquina1;
    public static javax.swing.JTextField totalMaquina2;
    public static javax.swing.JTextField totalMaquina3;
    public static javax.swing.JTextField totalMaquinas;
    public static javax.swing.JComboBox turno;
    // End of variables declaration//GEN-END:variables

}
