/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * alertaBombona.java
 *
 * Created on 01/01/2010, 16:51:30
 */

package Cadastro;
import auxiliar.*;
import javax.swing.JOptionPane;

/**
 *
 * @author ayrton monier
 */
public class alertaBombona extends javax.swing.JDialog {
public boolean extende = false;
    /** Creates new form alertaBombona */
    public alertaBombona(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        this.setSize(547, 285);//tamanho (largura, altura)
        this.setLocation(380, 282);//posicao (posicao hor, posic vert)

   }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        clientes = new javax.swing.JComboBox();
        contrato = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        contratoCliente = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btNaoEncontrei = new javax.swing.JButton();
        pesarBombona = new javax.swing.JButton();
        abreFecha = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lb3 = new javax.swing.JLabel();
        tf_qtBombPesada = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        lb5 = new javax.swing.JLabel();
        lb4 = new javax.swing.JLabel();
        lb6 = new javax.swing.JLabel();
        tf_qtBomb50 = new javax.swing.JTextField();
        tf_qtBomb20 = new javax.swing.JTextField();
        tf_qtBomb200 = new javax.swing.JTextField();
        lb_ = new javax.swing.JLabel();
        tf_situacao = new javax.swing.JTextField();
        lb = new javax.swing.JLabel();
        tf_diasColeta = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Localizalização de cliente - Sistema Serquip 1.0");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        clientes.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        clientes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "***********Selecione o cliente***********" }));
        clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientesActionPerformed(evt);
            }
        });

        contrato.setFont(new java.awt.Font("Tahoma", 1, 14));
        contrato.setToolTipText("Digite as iniciais do contrato");
        contrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contratoActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/procurar22.png"))); // NOI18N
        jButton4.setText("Ver nomes");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        contratoCliente.setEditable(false);
        contratoCliente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        contratoCliente.setToolTipText("Digite as iniciais do contrato");
        contratoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contratoClienteActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Parte do contrato:");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Nome do cliente que contem parte do contrato:");

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Contrato:");

        btNaoEncontrei.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/naoEncontreiBomb.png"))); // NOI18N
        btNaoEncontrei.setText("Não encontrei");
        btNaoEncontrei.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNaoEncontreiActionPerformed(evt);
            }
        });

        pesarBombona.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/bombona.png"))); // NOI18N
        pesarBombona.setText("Pesar bombona deste cliente");
        pesarBombona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesarBombonaActionPerformed(evt);
            }
        });

        abreFecha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/mostraTabela.png"))); // NOI18N
        abreFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abreFechaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(contrato, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(pesarBombona)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btNaoEncontrei, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE))
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(clientes, javax.swing.GroupLayout.Alignment.LEADING, 0, 348, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(contratoCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                            .addComponent(abreFecha, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(20, 20, 20)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(contrato, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(contratoCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(clientes, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(abreFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btNaoEncontrei, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pesarBombona, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Referências do contrato", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(0, 0, 0))); // NOI18N

        lb3.setText("Qtd. total de bombonas pesadas hoje por este cliente:");

        tf_qtBombPesada.setFont(new java.awt.Font("Tahoma", 0, 12));
        tf_qtBombPesada.setForeground(new java.awt.Color(255, 0, 0));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Informações de contrato"));

        lb5.setText("Qtd. bombonas de 50 L.:");

        lb4.setText("Qtd. bombonas de 20 L.:");

        lb6.setText("Qtd. bombonas de 200 L.:");

        tf_qtBomb50.setFont(new java.awt.Font("Tahoma", 0, 12));
        tf_qtBomb50.setForeground(new java.awt.Color(255, 0, 0));

        tf_qtBomb20.setFont(new java.awt.Font("Tahoma", 0, 12));
        tf_qtBomb20.setForeground(new java.awt.Color(255, 0, 0));

        tf_qtBomb200.setFont(new java.awt.Font("Tahoma", 0, 12));
        tf_qtBomb200.setForeground(new java.awt.Color(255, 0, 0));

        lb_.setText("Situação:");

        tf_situacao.setFont(new java.awt.Font("Tahoma", 0, 12));
        tf_situacao.setForeground(new java.awt.Color(255, 0, 0));

        lb.setText("Dia(s) de coleta(s):");

        tf_diasColeta.setFont(new java.awt.Font("Tahoma", 0, 12));
        tf_diasColeta.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb4)
                            .addComponent(lb5)
                            .addComponent(lb6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 170, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_qtBomb200)
                            .addComponent(tf_qtBomb50)
                            .addComponent(tf_qtBomb20, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb)
                            .addComponent(lb_))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_situacao, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                            .addComponent(tf_diasColeta, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lb_)
                    .addComponent(tf_situacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lb)
                    .addComponent(tf_diasColeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lb4)
                        .addGap(13, 13, 13)
                        .addComponent(lb5)
                        .addGap(13, 13, 13)
                        .addComponent(lb6))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(tf_qtBomb20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_qtBomb50, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_qtBomb200, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(lb3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addComponent(tf_qtBombPesada, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_qtBombPesada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb3))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, 0, 221, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        java.awt.Dimension dialogSize = getSize();
        setLocation((screenSize.width-dialogSize.width)/2,(screenSize.height-dialogSize.height)/2);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if(contrato.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Informe uma parte do contrato pesquisado", "Aviso", JOptionPane.WARNING_MESSAGE);
            contrato.requestFocus();
        }
        else
            //CHAMA O METODO QUE VAI ECHER O CONGOBOX de registros
            validaCadBomb.pesquisarClienteContrato();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void pesarBombonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesarBombonaActionPerformed
        if(contrato.getText().equals("")){
            JOptionPane.showMessageDialog(null, "DIGITE AS INICIAIS DO CONTRATO E PRESSIONE ENTER.", "Aviso", JOptionPane.WARNING_MESSAGE);
            contrato.requestFocus();
        }

        else if(clientes.getSelectedItem().toString().equals("***********Selecione o cliente***********")){
            JOptionPane.showMessageDialog(null, "SELECIONE UM CLIENTE NA LISTA.", "Aviso", JOptionPane.WARNING_MESSAGE);
            clientes.requestFocus();
        }

        else{
            CadastroBombona.contrato.setText(alertaBombona.contratoCliente.getText());
            validaCadBomb.pesquisaCliente();
            this.setVisible(false);
        }
    }//GEN-LAST:event_pesarBombonaActionPerformed

    private void clientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientesActionPerformed
        validaCadBomb.mostraReferenciasCli();
    }//GEN-LAST:event_clientesActionPerformed

    private void contratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contratoActionPerformed
        if(contrato.getText().equals(""))
            JOptionPane.showMessageDialog(null, "Digite os números iniciais do contrato.", "Aviso", JOptionPane.WARNING_MESSAGE);
        
        //CHAMA O METODO QUE VAI REECHER O CONGOBOX
        else
        validaCadBomb.pesquisarClienteContrato();

    }//GEN-LAST:event_contratoActionPerformed

    private void contratoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contratoClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contratoClienteActionPerformed

    private void abreFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abreFechaActionPerformed

        //extende ou nao o formulário
        if(extende == true){
            this.setSize(547, 285);//tamanho (largura, altura)
            extende = false;
            abreFecha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/mostraTabela.png")));
            abreFecha.setToolTipText("Esconder referências do cliente");
            this.setLocation(380, 282);//posicao (posicao hor, posic vert)

        }
        else{
            this.setSize(1035, 285);//tamanho (largura, altura)
            extende = true;
            abreFecha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/escondeTabela.png")));
            abreFecha.setToolTipText("Mostrar referências do cliente");
            this.setLocation(180, 282);//posicao (posicao hor, posic vert)
        }
    }//GEN-LAST:event_abreFechaActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        JOptionPane.showMessageDialog(null, "ESCOLHA O CLIENTE PARA EFETUAR A PESAGEM OU SE NÃO \nENCONTRAR CLIQUE NO BOTÃO [NÃO ENCONTREI]'.", "Aviso", JOptionPane.WARNING_MESSAGE);
        clientes.requestFocus();
    }//GEN-LAST:event_formWindowClosing

    private void btNaoEncontreiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNaoEncontreiActionPerformed
        CadastroBombona.contrato.setText("0");
        CadastroBombona.cliente.setText("Desconhecido");
        CadastroBombona.escolhaCapacidade.requestFocus();
        validaCadBomb.tipoBombonaPesada = "Descon.";
        this.setVisible(false);
    }//GEN-LAST:event_btNaoEncontreiActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                alertaBombona dialog = new alertaBombona(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton abreFecha;
    private javax.swing.JButton btNaoEncontrei;
    public static javax.swing.JComboBox clientes;
    public static javax.swing.JTextField contrato;
    public static javax.swing.JTextField contratoCliente;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    public static javax.swing.JLabel lb;
    public static javax.swing.JLabel lb3;
    public static javax.swing.JLabel lb4;
    public static javax.swing.JLabel lb5;
    public static javax.swing.JLabel lb6;
    public static javax.swing.JLabel lb_;
    private javax.swing.JButton pesarBombona;
    public static javax.swing.JTextField tf_diasColeta;
    public static javax.swing.JTextField tf_qtBomb20;
    public static javax.swing.JTextField tf_qtBomb200;
    public static javax.swing.JTextField tf_qtBomb50;
    public static javax.swing.JTextField tf_qtBombPesada;
    public static javax.swing.JTextField tf_situacao;
    // End of variables declaration//GEN-END:variables

}
