/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CadastroBombona.java
 *
 * Created on 05/11/2009, 22:16:43
 */

package Cadastro;
import javax.swing.*;
import auxiliar.*;
import auxiliar.Data;
import javax.swing.text.MaskFormatter;


/**
 *
 * @author ayrton monier
 */
public class CadastroBombona extends javax.swing.JDialog {

    MaskFormatter formatoPesoBruto;
    String caracterDigitado;
    public boolean extende = false;
    public static int navega = 0;
    
    /** Creates new form CadastroBombona */
    public CadastroBombona(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        this.setSize(1228, 465);
        //chama metodo auxiliar que inicia componentes
        validaCadBomb.iniciaComponentes();


    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btExcluir = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        qtTotal = new javax.swing.JTextField();
        totalBruto = new javax.swing.JTextField();
        totalLiquido = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        totalExcedido = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        totalBExtra = new javax.swing.JTextField();
        totalBContrato = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        totalDesconhedida = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        totalAcumulada = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        totalEmDia = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaBombona = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        cliente = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        escolhaCapacidade = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        contrato = new javax.swing.JTextField();
        btProcurar = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        pesoLiquido = new javax.swing.JFormattedTextField();
        jPanel13 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        pesoExcedido = new javax.swing.JFormattedTextField();
        jPanel12 = new javax.swing.JPanel();
        tipoBombona = new javax.swing.JFormattedTextField();
        jPanel14 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        try{

            formatoPesoBruto = new MaskFormatter("##.##");
            formatoPesoBruto.setPlaceholderCharacter('0');
        }
        catch(Exception erro){

            JOptionPane.showMessageDialog(null, "Não foi possível inserir a mascara no campo\nERRO: "+erro);
        }
        pesoBruto = new JFormattedTextField(formatoPesoBruto);
        jPanel15 = new javax.swing.JPanel();
        codigoBomb = new javax.swing.JFormattedTextField();
        btNovo = new javax.swing.JButton();
        confirmaPeso = new javax.swing.JButton();
        btUltimo = new javax.swing.JButton();
        btProximo = new javax.swing.JButton();
        btAnterior = new javax.swing.JButton();
        btPrimeiro = new javax.swing.JButton();
        mostra = new javax.swing.JButton();
        pesarAcumuladas = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        status = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Controle de pesagem de bombonas - Sistema Serquip 1.0");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        btExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/excluir.png"))); // NOI18N
        btExcluir.setToolTipText("Excluir registro");
        btExcluir.setEnabled(false);
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/sair.png"))); // NOI18N
        jButton12.setMnemonic('e');
        jButton12.setToolTipText("Sair");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        qtTotal.setBackground(new java.awt.Color(204, 204, 255));
        qtTotal.setEditable(false);
        qtTotal.setFont(new java.awt.Font("Tahoma", 1, 18));
        qtTotal.setForeground(new java.awt.Color(255, 0, 0));
        qtTotal.setText("0");
        qtTotal.setToolTipText("Quantidade de bombonas pesadas durante este turno");
        qtTotal.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Qtd. do turno", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(0, 0, 0))); // NOI18N
        qtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qtTotalActionPerformed(evt);
            }
        });

        totalBruto.setBackground(new java.awt.Color(204, 204, 255));
        totalBruto.setEditable(false);
        totalBruto.setFont(new java.awt.Font("Tahoma", 1, 18));
        totalBruto.setForeground(new java.awt.Color(255, 0, 0));
        totalBruto.setText("0.0");
        totalBruto.setToolTipText("Total bruto acumulado durante este turno");
        totalBruto.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Total bruto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(0, 0, 0))); // NOI18N

        totalLiquido.setBackground(new java.awt.Color(204, 204, 255));
        totalLiquido.setEditable(false);
        totalLiquido.setFont(new java.awt.Font("Tahoma", 1, 18));
        totalLiquido.setForeground(new java.awt.Color(255, 0, 0));
        totalLiquido.setText("0.0");
        totalLiquido.setToolTipText("Total líquido acumulado durante este turno");
        totalLiquido.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Total líquido", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(0, 0, 0))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel7.setText("Kg");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel8.setText("Kg");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel9.setText("Und.");

        totalExcedido.setBackground(new java.awt.Color(204, 204, 255));
        totalExcedido.setEditable(false);
        totalExcedido.setFont(new java.awt.Font("Tahoma", 1, 18));
        totalExcedido.setForeground(new java.awt.Color(255, 0, 0));
        totalExcedido.setText("0.0");
        totalExcedido.setToolTipText("Total excedido acumulado durante este turno");
        totalExcedido.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Total excedido", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(0, 0, 0))); // NOI18N

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel22.setText("Kg");

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel23.setText("Und.");

        totalBExtra.setBackground(new java.awt.Color(204, 204, 255));
        totalBExtra.setEditable(false);
        totalBExtra.setFont(new java.awt.Font("Tahoma", 1, 18));
        totalBExtra.setForeground(new java.awt.Color(255, 0, 0));
        totalBExtra.setText("0");
        totalBExtra.setToolTipText("Quantidade de bombonas extras pesadas durante este turno");
        totalBExtra.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Total extra", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(0, 0, 0))); // NOI18N

        totalBContrato.setBackground(new java.awt.Color(204, 204, 255));
        totalBContrato.setEditable(false);
        totalBContrato.setFont(new java.awt.Font("Tahoma", 1, 18));
        totalBContrato.setForeground(new java.awt.Color(255, 0, 0));
        totalBContrato.setText("0");
        totalBContrato.setToolTipText("Quantidade de bombonas de contrato pesadas durante este turno");
        totalBContrato.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Total Contrato", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(0, 0, 0))); // NOI18N

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel24.setText("Und.");

        totalDesconhedida.setBackground(new java.awt.Color(204, 204, 255));
        totalDesconhedida.setEditable(false);
        totalDesconhedida.setFont(new java.awt.Font("Tahoma", 1, 18));
        totalDesconhedida.setForeground(new java.awt.Color(255, 0, 0));
        totalDesconhedida.setText("0");
        totalDesconhedida.setToolTipText("Quantidade de bombonas desconhecidas pesadas durante este turno");
        totalDesconhedida.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Total desc.", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(0, 0, 0))); // NOI18N

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel25.setText("Und.");

        totalAcumulada.setBackground(new java.awt.Color(204, 204, 255));
        totalAcumulada.setEditable(false);
        totalAcumulada.setFont(new java.awt.Font("Tahoma", 1, 18));
        totalAcumulada.setForeground(new java.awt.Color(255, 0, 0));
        totalAcumulada.setText("0");
        totalAcumulada.setToolTipText("Quantidade de bombonas acumuladas pesadas durante este turno");
        totalAcumulada.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Total acumul.", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(0, 0, 0))); // NOI18N
        totalAcumulada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalAcumuladaActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel10.setText("Und.");

        totalEmDia.setBackground(new java.awt.Color(204, 204, 255));
        totalEmDia.setEditable(false);
        totalEmDia.setFont(new java.awt.Font("Tahoma", 1, 18));
        totalEmDia.setForeground(new java.awt.Color(255, 0, 0));
        totalEmDia.setText("0");
        totalEmDia.setToolTipText("Quantidade de bombonas em dia pesadas durante este turno ");
        totalEmDia.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Total em dia", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(0, 0, 0))); // NOI18N
        totalEmDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalEmDiaActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel13.setText("Und.");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(totalBruto, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(totalBExtra, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel23))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(totalDesconhedida, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel25)
                        .addGap(94, 94, 94)
                        .addComponent(totalEmDia, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 158, Short.MAX_VALUE)
                        .addComponent(totalLiquido, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addGap(146, 146, 146)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(totalExcedido, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel22))
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(totalAcumulada, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addGap(67, 67, 67)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(qtTotal)
                    .addComponent(totalBContrato, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24)
                    .addComponent(jLabel9))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(totalExcedido)
                    .addComponent(jLabel22)
                    .addComponent(totalBruto, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(totalBContrato, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel24))
                    .addComponent(jLabel7)
                    .addComponent(totalLiquido)
                    .addComponent(jLabel8))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(totalEmDia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                            .addComponent(totalDesconhedida, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                            .addComponent(qtTotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(totalBExtra, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel23))
                            .addComponent(jLabel25, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(totalAcumulada, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel13)))
                .addContainerGap())
        );

        tabelaBombona.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tabelaBombona.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Contrato", "Capacidade", "Peso bruto", "Peso líquido", "Peso excedido", "Tipo", "Pesagem", "Hora da pesagem"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaBombona.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaBombonaMouseClicked(evt);
            }
        });
        tabelaBombona.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tabelaBombonaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tabelaBombonaKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaBombona);

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12), new java.awt.Color(0, 0, 0)), "Nome / Razão social", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14), new java.awt.Color(0, 0, 0))); // NOI18N

        cliente.setEditable(false);
        cliente.setFont(new java.awt.Font("Tahoma", 1, 18));
        cliente.setForeground(new java.awt.Color(0, 0, 102));
        cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cliente, javax.swing.GroupLayout.DEFAULT_SIZE, 569, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(cliente)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Capacidade da Bombona", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N

        escolhaCapacidade.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        escolhaCapacidade.setForeground(new java.awt.Color(0, 0, 153));
        escolhaCapacidade.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "200", "50", "20" }));
        escolhaCapacidade.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                escolhaCapacidadeFocusLost(evt);
            }
        });
        escolhaCapacidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                escolhaCapacidadeKeyTyped(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18));
        jLabel11.setText("Litros");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(escolhaCapacidade, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(escolhaCapacidade, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Contrato", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14), new java.awt.Color(0, 0, 0))); // NOI18N

        contrato.setFont(new java.awt.Font("Tahoma", 1, 24));
        contrato.setForeground(new java.awt.Color(0, 0, 102));
        contrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contratoActionPerformed(evt);
            }
        });

        btProcurar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/procurar32.png"))); // NOI18N
        btProcurar.setMnemonic('l');
        btProcurar.setToolTipText("Localizar cliente");
        btProcurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btProcurarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(contrato, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btProcurar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                .addComponent(contrato)
                .addComponent(btProcurar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Peso líquido", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14), new java.awt.Color(0, 0, 0))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18));
        jLabel4.setText("Kg");

        pesoLiquido.setEditable(false);
        pesoLiquido.setForeground(new java.awt.Color(0, 0, 153));
        pesoLiquido.setFont(new java.awt.Font("Tahoma", 1, 24));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pesoLiquido, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(pesoLiquido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPanel13.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Peso excedido", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14), new java.awt.Color(0, 0, 0))); // NOI18N

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18));
        jLabel12.setText("Kg");

        pesoExcedido.setEditable(false);
        pesoExcedido.setForeground(new java.awt.Color(0, 0, 153));
        pesoExcedido.setFont(new java.awt.Font("Tahoma", 1, 24));

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(pesoExcedido, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pesoExcedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tipo de bombona", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14), new java.awt.Color(0, 0, 0))); // NOI18N

        tipoBombona.setEditable(false);
        tipoBombona.setForeground(new java.awt.Color(0, 0, 153));
        tipoBombona.setFont(new java.awt.Font("Tahoma", 1, 22));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tipoBombona, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addComponent(tipoBombona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel14.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Peso bruto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14), new java.awt.Color(0, 0, 0))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18));
        jLabel5.setText("Kg");

        pesoBruto.setForeground(new java.awt.Color(0, 0, 153));
        pesoBruto.setFont(new java.awt.Font("Tahoma", 1, 24));
        pesoBruto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesoBrutoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pesoBruto, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(pesoBruto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPanel15.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cód. da bombona", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14), new java.awt.Color(0, 0, 0))); // NOI18N

        codigoBomb.setEditable(false);
        codigoBomb.setForeground(new java.awt.Color(0, 0, 153));
        codigoBomb.setFont(new java.awt.Font("Tahoma", 1, 12));

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(codigoBomb, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addComponent(codigoBomb, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                    .addComponent(jPanel13, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        btNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/adicionar.png"))); // NOI18N
        btNovo.setMnemonic('a');
        btNovo.setToolTipText("Novo registro");
        btNovo.setAutoscrolls(true);
        btNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNovoActionPerformed(evt);
            }
        });

        confirmaPeso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ok.png"))); // NOI18N
        confirmaPeso.setMnemonic('s');
        confirmaPeso.setToolTipText("Confirmar registro");
        confirmaPeso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmaPesoActionPerformed(evt);
            }
        });

        btUltimo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ultimo.png"))); // NOI18N
        btUltimo.setToolTipText("Último registro");
        btUltimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUltimoActionPerformed(evt);
            }
        });

        btProximo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/proximo.png"))); // NOI18N
        btProximo.setToolTipText("Próximo registro");
        btProximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btProximoActionPerformed(evt);
            }
        });

        btAnterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/anterior.png"))); // NOI18N
        btAnterior.setToolTipText("Registro anterior");
        btAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAnteriorActionPerformed(evt);
            }
        });

        btPrimeiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/primeiro.png"))); // NOI18N
        btPrimeiro.setToolTipText("Primeiro registro");
        btPrimeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPrimeiroActionPerformed(evt);
            }
        });

        mostra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/mostraTabela.png"))); // NOI18N
        mostra.setToolTipText("Mostrar tabela");
        mostra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostraActionPerformed(evt);
            }
        });

        pesarAcumuladas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/acumuladas.png"))); // NOI18N
        pesarAcumuladas.setText("Acumuladas");
        pesarAcumuladas.setToolTipText("Pesar acumuladas");
        pesarAcumuladas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesarAcumuladasActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel1.setText("Status: ");

        status.setFont(new java.awt.Font("Tahoma", 1, 18));
        status.setText("Pesando bombona em dia...");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(status))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btPrimeiro, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btProximo, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btUltimo, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(confirmaPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mostra)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 472, Short.MAX_VALUE)
                        .addComponent(pesarAcumuladas))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1138, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(status))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(mostra, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                        .addComponent(pesarAcumuladas, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btPrimeiro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btAnterior, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btProximo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btUltimo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(confirmaPeso, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btNovo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btExcluir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton12, javax.swing.GroupLayout.Alignment.TRAILING)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        java.awt.Dimension dialogSize = getSize();
        setLocation((screenSize.width-dialogSize.width)/2,(screenSize.height-dialogSize.height)/2);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
       int opcao_escolhida = JOptionPane.showConfirmDialog(null, "DESEJA REALMENTE SAIR?", "Sair", JOptionPane.YES_NO_OPTION);

       if(opcao_escolhida == JOptionPane.YES_OPTION){
           validaCadBomb.fechaConexao();
           dispose();
       }
       else
           return;
}//GEN-LAST:event_jButton12ActionPerformed

    private void qtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qtTotalActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_qtTotalActionPerformed

    private void clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clienteActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_clienteActionPerformed

    private void escolhaCapacidadeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_escolhaCapacidadeKeyTyped
        if(escolhaCapacidade.getSelectedItem().equals("")){
            JOptionPane.showMessageDialog(null, "ESCOLHA A CAPACIDADE DA BOMBONA", "aviso", JOptionPane.WARNING_MESSAGE);
        }
        else{
            pesoBruto.requestFocus();    
        }
}//GEN-LAST:event_escolhaCapacidadeKeyTyped

    private void contratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contratoActionPerformed
            validaCadBomb.pesquisaCliente();
}//GEN-LAST:event_contratoActionPerformed

    private void btProcurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btProcurarActionPerformed
            validaCadBomb.pesquisaCliente();
        
}//GEN-LAST:event_btProcurarActionPerformed

    private void confirmaPesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmaPesoActionPerformed
      
        try{

        validaCadBomb.defineValores();

        }//fim try
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "PREENCHA OS CAMPOS:\n1. CONTRATO\n2. CAPACIDADE DA BOMBONA\n3. PESO BRUTO", "aviso", JOptionPane.WARNING_MESSAGE);
            contrato.requestFocus();
        }
    
    
}//GEN-LAST:event_confirmaPesoActionPerformed

    private void pesoBrutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesoBrutoActionPerformed

        try{

        validaCadBomb.defineValores();

        }//fim try
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "PREENCHA OS CAMPOS:\n1. CONTRATO\n2. CAPACIDADE DA BOMBONA\n3. PESO BRUTO", "aviso", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_pesoBrutoActionPerformed

    private void btNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNovoActionPerformed
        
        if(codigoBomb.getText().length() >= 1){


                validaCadBomb.atualizaPainel();
                validaCadBomb.habilitaCampos(true);
                validaCadBomb.limpaCamposCadBomb();
                btExcluir.setEnabled(false);
        }
        else if(cliente.getText().length() > 0){
            //pergunta se que limpar realmente
            int opcao = JOptionPane.showConfirmDialog(null , "ISSO APAGARÁ O REGISTRO ATUAL, DESEJA CONTINUAR?", "Novo registro", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);

            if(opcao == JOptionPane.YES_OPTION){

                validaCadBomb.atualizaPainel();
                validaCadBomb.habilitaCampos(true);
                validaCadBomb.limpaCamposCadBomb();

                btExcluir.setEnabled(false);
            }
            else{

                btExcluir.setEnabled(true);
                validaCadBomb.habilitaCampos(true);
                escolhaCapacidade.requestFocus();
                return;
            }
        }
        else{
                btExcluir.setEnabled(false);
                validaCadBomb.habilitaCampos(true);
                validaCadBomb.limpaCamposCadBomb();
        }

    }//GEN-LAST:event_btNovoActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
       int opcao_escolhida = JOptionPane.showConfirmDialog(null, "DESEJA REALMENTE SAIR?", "Sair", JOptionPane.YES_NO_OPTION);

       if(opcao_escolhida == JOptionPane.YES_OPTION){
           validaCadBomb.fechaConexao();
           dispose();
       }
       else
           return;
    }//GEN-LAST:event_formWindowClosing

    private void btPrimeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPrimeiroActionPerformed
        navega = 1;
        if(codigoBomb.getText().isEmpty() && cliente.getText().length() > 0){
            int opc = JOptionPane.showConfirmDialog(null, "O REGISTRO ATUAL SERÁ APAGADO, DESEJA CONTINUAR?", "Aviso", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);

            if(opc == JOptionPane.YES_OPTION){
                //posição do registro
                validaCadBomb.direcao = "primeiro";
                //chama o metodo que resolve a navegação dos botoes
                validaCadBomb.btNavega();
                validaCadBomb.habilitaCampos(false);
            }
            else{
               contrato.requestFocus();
               return;
            }
        }
        else{
                //posição do registro
                validaCadBomb.direcao = "primeiro";
                //chama o metodo que resolve a navegação dos botoes
                validaCadBomb.btNavega();
                validaCadBomb.habilitaCampos(false);
        }
    }//GEN-LAST:event_btPrimeiroActionPerformed

    private void btAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAnteriorActionPerformed
        navega = 1;

        if(codigoBomb.getText().isEmpty() && cliente.getText().length() > 0){
            int opc = JOptionPane.showConfirmDialog(null, "O REGISTRO ATUAL SERÁ APAGADO, DESEJA CONTINUAR?", "Aviso", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);

            if(opc == JOptionPane.YES_OPTION){
                //posição do registro
                validaCadBomb.direcao = "primeiro";
                //chama o metodo que resolve a navegação dos botoes
                validaCadBomb.btNavega();
                validaCadBomb.habilitaCampos(false);

            }
            else{
               contrato.requestFocus();
               return;
            }
        }
        else{
                //posição do registro
                validaCadBomb.direcao = "anterior";
                //chama o metodo que resolve a navegação dos botoes
                validaCadBomb.btNavega();
                validaCadBomb.habilitaCampos(false);

        }
    }//GEN-LAST:event_btAnteriorActionPerformed

    private void btProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btProximoActionPerformed
        navega = 2;

        if(codigoBomb.getText().isEmpty() && cliente.getText().length() > 0){
            int opc = JOptionPane.showConfirmDialog(null, "O REGISTRO ATUAL SERÁ APAGADO, DESEJA CONTINUAR?", "Aviso", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);

            if(opc == JOptionPane.YES_OPTION){
                //posição do registro
                validaCadBomb.direcao = "ultimo";
                //chama o metodo que resolve a navegação dos botoes
                validaCadBomb.btNavega();
                validaCadBomb.habilitaCampos(false);
            }
            else
               return;
        }
        else{
                //posição do registro
                validaCadBomb.direcao = "proximo";
                //chama o metodo que resolve a navegação dos botoes
                validaCadBomb.btNavega();
                validaCadBomb.habilitaCampos(false);
        }
    }//GEN-LAST:event_btProximoActionPerformed

    private void btUltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUltimoActionPerformed
        navega = 2;

        if(codigoBomb.getText().isEmpty() && cliente.getText().length() > 0){
            int opc = JOptionPane.showConfirmDialog(null, "O REGISTRO ATUAL SERÁ APAGADO, DESEJA CONTINUAR?", "Aviso", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);

            if(opc == JOptionPane.YES_OPTION){
                //posição do registro
                validaCadBomb.direcao = "ultimo";
                //chama o metodo que resolve a navegação dos botoes
                validaCadBomb.btNavega();
                validaCadBomb.habilitaCampos(false);
            
            }
            else{
               contrato.requestFocus();
               return;
            }
        }
        else{
                //posição do registro
                validaCadBomb.direcao = "ultimo";
                //chama o metodo que resolve a navegação dos botoes
                validaCadBomb.btNavega();
                validaCadBomb.habilitaCampos(false);
                
        }
    }//GEN-LAST:event_btUltimoActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
         if(codigoBomb.getText().isEmpty()){
             JOptionPane.showMessageDialog(null, "SELECIONE UM REGISTRO ATRAVÉS DOS BOTÕES DE NAVEGAÇÃO!", "Aviso", JOptionPane.WARNING_MESSAGE);
             CadastroBombona.contrato.requestFocus();
         }
         else{
         //chama metodo para configurar a telinha de exclusao
         validaCadBomb.configuraExclusao();

         }
    }//GEN-LAST:event_btExcluirActionPerformed

    private void mostraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostraActionPerformed
        //extende ou nao o formulário
        if(extende == true){
            this.setSize(1228, 465);
            extende = false;
            mostra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/mostraTabela.png")));
            mostra.setToolTipText("Mostrar tabela");

        }
        else{
            this.setSize(1228, 705);
            extende = true;
            mostra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/escondeTabela.png")));
            mostra.setToolTipText("Esconder tabela");
        }
    }//GEN-LAST:event_mostraActionPerformed

    private void pesarAcumuladasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesarAcumuladasActionPerformed
        Data.dataOntem();

        //JOptionPane.showMessageDialog(null, Data.dataOntem);

        if(pesarAcumuladas.isSelected() == true){
            validaCadBomb.dataPesagem = Data.dataOntem;
            validaCadBomb.tipoPesagem = "Acumulada";

            status.setForeground(new java.awt.Color(255, 0, 0));
            status.setText("Pesando bombona acumulada...");
            //JOptionPane.showMessageDialog(null, "Data de ontem: "+validaCadBomb.dataPesagem+"\nTipo de pesagem: "+validaCadBomb.tipoPesagem);

        }
        else{
            validaCadBomb.dataPesagem = validaLogin.DATAFORMAT;
            validaCadBomb.tipoPesagem = "Em dia";

            status.setForeground(new java.awt.Color(0, 0, 0));
            status.setText("Pesando bombona em dia...");
            //JOptionPane.showMessageDialog(null, "Data de hoje: "+validaCadBomb.dataPesagem+"\nTipo de pesagem: "+validaCadBomb.tipoPesagem);
        }
        //foco para o campo contrato
        contrato.requestFocus();

    }//GEN-LAST:event_pesarAcumuladasActionPerformed

    private void totalAcumuladaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalAcumuladaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalAcumuladaActionPerformed

    private void totalEmDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalEmDiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalEmDiaActionPerformed

    private void tabelaBombonaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaBombonaMouseClicked
        validaCadBomb.cliqueGrid();
    }//GEN-LAST:event_tabelaBombonaMouseClicked

    private void tabelaBombonaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabelaBombonaKeyReleased
        validaCadBomb.cliqueGrid();
    }//GEN-LAST:event_tabelaBombonaKeyReleased

    private void tabelaBombonaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabelaBombonaKeyTyped
        if(evt.getKeyChar() == '')
            validaCadBomb.configuraExclusao();

    }//GEN-LAST:event_tabelaBombonaKeyTyped

    private void escolhaCapacidadeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_escolhaCapacidadeFocusLost
            validaCadBomb.defineTipoBombona();
    }//GEN-LAST:event_escolhaCapacidadeFocusLost

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CadastroBombona dialog = new CadastroBombona(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAnterior;
    public static javax.swing.JButton btExcluir;
    public static javax.swing.JButton btNovo;
    private javax.swing.JButton btPrimeiro;
    private javax.swing.JButton btProcurar;
    private javax.swing.JButton btProximo;
    private javax.swing.JButton btUltimo;
    public static javax.swing.JTextField cliente;
    public static javax.swing.JFormattedTextField codigoBomb;
    public static javax.swing.JButton confirmaPeso;
    public static javax.swing.JTextField contrato;
    public static javax.swing.JComboBox escolhaCapacidade;
    private javax.swing.JButton jButton12;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JButton mostra;
    public static javax.swing.JToggleButton pesarAcumuladas;
    public static javax.swing.JFormattedTextField pesoBruto;
    public static javax.swing.JFormattedTextField pesoExcedido;
    public static javax.swing.JFormattedTextField pesoLiquido;
    public static javax.swing.JTextField qtTotal;
    public static javax.swing.JLabel status;
    public static javax.swing.JTable tabelaBombona;
    public static javax.swing.JFormattedTextField tipoBombona;
    public static javax.swing.JTextField totalAcumulada;
    public static javax.swing.JTextField totalBContrato;
    public static javax.swing.JTextField totalBExtra;
    public static javax.swing.JTextField totalBruto;
    public static javax.swing.JTextField totalDesconhedida;
    public static javax.swing.JTextField totalEmDia;
    public static javax.swing.JTextField totalExcedido;
    public static javax.swing.JTextField totalLiquido;
    // End of variables declaration//GEN-END:variables

}
