/*
 * CadastroCliente.java
 *
 * Created on 27 de Setembro de 2009, 03:03
 */

package Cadastro;

import javax.swing.text.MaskFormatter;
import javax.swing.*;
import auxiliar.validaCadCli;
//import java.util.Locale;
import RelatorioJava.clientesAtivos;//chama lista de clientes
import RelatorioJava.clienteAtivo;//chama unico cliente
import RelatorioJava.clienteSuspensoIndeterminado;
import RelatorioJava.clientesSuspensos;
import RelatorioJava.clienteCancelado;
import RelatorioJava.clientesCancelados;
import RelatorioJava.relacaoSuspensoVencido;
import RelatorioJava.relacaoSuspensosVencidos;
import RelatorioJava.clientesSuspensosIndeterminados;
import RelatorioJava.relacaoSuspenso;
import auxiliar.validaLogin;

/**
 *
 * @author  ayrton monier
 */
public class CadastroCliente extends javax.swing.JFrame {
    public static String situacaoEscolhida;
    public static int somaBomb;
    public static int navega;
    //se tiver gravando cliente a condição fica true.
    public static boolean gravandoCliente = false;

    MaskFormatter formFone, formData, formHora;

    /** Creates new form CadastroCliente */
    public CadastroCliente() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        validaCadCli.iniciaComponentes();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        botoesOrdenacao = new javax.swing.ButtonGroup();
        selecaoSituacao = new javax.swing.ButtonGroup();
        grupoSituacaoSusDeter = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        nomeCli = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        ruaCli = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        ptReferenciaCli = new javax.swing.JTextField();
        responsavelCli = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        try{
            formHora = new MaskFormatter("##:##");
            formHora.setPlaceholderCharacter('_');
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Não foi possível inserir a máscara no campo, erro: "+e);
        }
        hrFun_de = new JFormattedTextField(formHora);
        try{
            formHora = new MaskFormatter("##:##");
            formHora.setPlaceholderCharacter('_');
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Não foi possível inserir a máscara no campo, erro: "+e);
        }
        hrFunc_a = new JFormattedTextField(formHora);
        codigoCli = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        try{

            formFone = new MaskFormatter("(##)####-####");
            formFone.setPlaceholderCharacter('_');
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Não foi possível inserir a máscara no campo, erro: "+e);
        }
        foneCli = new JFormattedTextField(formFone);
        jLabel29 = new javax.swing.JLabel();
        obs = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        orderNome = new javax.swing.JRadioButton();
        orderCodigo = new javax.swing.JRadioButton();
        orderBairro = new javax.swing.JRadioButton();
        bairroCli = new javax.swing.JComboBox();
        cidadeCli = new javax.swing.JComboBox();
        ufCli = new javax.swing.JComboBox();
        jLabel31 = new javax.swing.JLabel();
        addBairro = new javax.swing.JButton();
        addCidade = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaCliente = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        contratoCli = new javax.swing.JTextField();
        painelPeriodoColeta = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        inicioColeta = new javax.swing.JComboBox();
        fimColeta = new javax.swing.JComboBox();
        jLabel16 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        qtTotalBomb = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel38 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        qtBomb200 = new javax.swing.JComboBox();
        qtBomb50 = new javax.swing.JComboBox();
        qtBomb20 = new javax.swing.JComboBox();
        painelDiaColeta = new javax.swing.JPanel();
        diaColeta = new javax.swing.JTextField();
        btAddDiaColeta = new javax.swing.JButton();
        situacaoCli = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        btImprimirFicha = new javax.swing.JButton();
        btCancelarCli = new javax.swing.JButton();
        btAnteriorReg = new javax.swing.JButton();
        btProximoReg = new javax.swing.JButton();
        btPrimeiroReg = new javax.swing.JButton();
        btAddCli = new javax.swing.JButton();
        btUltimoReg = new javax.swing.JButton();
        btGravaCli = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        caixaPesquisaNome = new javax.swing.JTextField();
        caixaPesquisaContrato = new javax.swing.JTextField();
        btExcluirCli = new javax.swing.JButton();
        btAtivos = new javax.swing.JToggleButton();
        btCancelados = new javax.swing.JToggleButton();
        btSuspensosDeterminados = new javax.swing.JToggleButton();
        btTodos = new javax.swing.JToggleButton();
        btSuspenderCli = new javax.swing.JButton();
        btImprimirLista = new javax.swing.JButton();
        btSuspensosIndeterminados = new javax.swing.JToggleButton();
        infoSituacao = new javax.swing.JButton();
        listaClientes = new javax.swing.JComboBox();
        btSair = new javax.swing.JButton();
        lbQtdCli = new javax.swing.JLabel();
        rb_emDia = new javax.swing.JRadioButton();
        rb_vencidos = new javax.swing.JRadioButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Controle de Clientes - Sistema Serquip 1.0"); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Informações do Cliente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 0, 0))); // NOI18N

        jLabel3.setText("Nome / Razão Social:"); // NOI18N

        nomeCli.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nomeCli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nomeCliKeyTyped(evt);
            }
        });

        jLabel20.setText("Fone:"); // NOI18N

        jLabel23.setText("Rua: "); // NOI18N

        ruaCli.setFont(new java.awt.Font("Tahoma", 1, 14));
        ruaCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ruaCliActionPerformed(evt);
            }
        });

        jLabel25.setText("Responsável:"); // NOI18N

        jLabel26.setText("Pt. de Referência:"); // NOI18N

        ptReferenciaCli.setFont(new java.awt.Font("Tahoma", 1, 14));
        ptReferenciaCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ptReferenciaCliActionPerformed(evt);
            }
        });

        responsavelCli.setFont(new java.awt.Font("Tahoma", 1, 14));
        responsavelCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                responsavelCliActionPerformed(evt);
            }
        });

        jLabel27.setText("Cidade:"); // NOI18N

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Horário de Funcionamento"));

        jLabel9.setText("de:"); // NOI18N

        jLabel12.setText("as:"); // NOI18N

        hrFun_de.setFont(new java.awt.Font("Tahoma", 1, 18));

        hrFunc_a.setFont(new java.awt.Font("Tahoma", 1, 18));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hrFun_de, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hrFunc_a, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                .addComponent(jLabel12)
                .addComponent(hrFun_de, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(hrFunc_a, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel9))
        );

        codigoCli.setEditable(false);
        codigoCli.setFont(new java.awt.Font("Tahoma", 1, 14));
        codigoCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigoCliActionPerformed(evt);
            }
        });

        jLabel33.setText("Cod.:"); // NOI18N

        foneCli.setFont(new java.awt.Font("Tahoma", 1, 14));

        jLabel29.setText("Observação:"); // NOI18N

        obs.setFont(new java.awt.Font("Tahoma", 1, 14));

        jLabel30.setText("Bairro:"); // NOI18N

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Ordenação"));

        botoesOrdenacao.add(orderNome);
        orderNome.setSelected(true);
        orderNome.setText("Nome / Razão Social"); // NOI18N
        orderNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderNomeActionPerformed(evt);
            }
        });

        botoesOrdenacao.add(orderCodigo);
        orderCodigo.setText("Código"); // NOI18N
        orderCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderCodigoActionPerformed(evt);
            }
        });

        botoesOrdenacao.add(orderBairro);
        orderBairro.setText("Bairro"); // NOI18N
        orderBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderBairroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(orderNome)
                    .addComponent(orderCodigo)
                    .addComponent(orderBairro))
                .addContainerGap(204, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(orderNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(orderCodigo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(orderBairro)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        ufCli.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));
        ufCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ufCliActionPerformed(evt);
            }
        });

        jLabel31.setText("UF:"); // NOI18N

        addBairro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/adicionar22.png"))); // NOI18N
        addBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBairroActionPerformed(evt);
            }
        });

        addCidade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/adicionar22.png"))); // NOI18N
        addCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCidadeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel20)
                    .addComponent(jLabel23)
                    .addComponent(jLabel33)
                    .addComponent(jLabel26)
                    .addComponent(jLabel29))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(codigoCli, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nomeCli, javax.swing.GroupLayout.DEFAULT_SIZE, 846, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(ruaCli, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel30)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bairroCli, 0, 233, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(addBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ptReferenciaCli, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 397, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(foneCli, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(responsavelCli, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(obs, javax.swing.GroupLayout.DEFAULT_SIZE, 659, Short.MAX_VALUE))
                        .addGap(14, 14, 14)
                        .addComponent(jLabel27)
                        .addGap(4, 4, 4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cidadeCli, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(addCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14)
                                .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ufCli, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.CENTER, jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel23)
                .addGap(134, 134, 134))
            .addGroup(javax.swing.GroupLayout.Alignment.CENTER, jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel30)
                .addGap(134, 134, 134))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codigoCli, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel33)
                    .addComponent(nomeCli, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ufCli, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                            .addComponent(jLabel31)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cidadeCli, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                                .addComponent(jLabel27))
                            .addComponent(addBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bairroCli, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                            .addComponent(ruaCli, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel20)
                                    .addComponent(responsavelCli, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(foneCli, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel26)
                                    .addComponent(ptReferenciaCli, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel29)
                            .addComponent(obs, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        tabelaCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código ", "Contrato", "Nome / Razão social", "Bairro", "Cidade", "UF", "Fone", "Responsável", "Situação"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaCliente.setToolTipText("Tabela de controle de clientes");
        tabelaCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaClienteMouseClicked(evt);
            }
        });
        tabelaCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tabelaClienteKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(tabelaCliente);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Informações do Contrato", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 0, 0))); // NOI18N

        jLabel2.setText("Contrato:"); // NOI18N

        contratoCli.setFont(new java.awt.Font("Tahoma", 1, 36));
        contratoCli.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                contratoCliMouseClicked(evt);
            }
        });
        contratoCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contratoCliActionPerformed(evt);
            }
        });

        painelPeriodoColeta.setBorder(javax.swing.BorderFactory.createTitledBorder("Período da Coleta"));

        jLabel14.setText("De:"); // NOI18N

        jLabel15.setText("a:"); // NOI18N

        inicioColeta.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "" }));

        fimColeta.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "" }));

        jLabel16.setText("de cada mês"); // NOI18N

        javax.swing.GroupLayout painelPeriodoColetaLayout = new javax.swing.GroupLayout(painelPeriodoColeta);
        painelPeriodoColeta.setLayout(painelPeriodoColetaLayout);
        painelPeriodoColetaLayout.setHorizontalGroup(
            painelPeriodoColetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPeriodoColetaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inicioColeta, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fimColeta, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel16)
                .addContainerGap(52, Short.MAX_VALUE))
        );
        painelPeriodoColetaLayout.setVerticalGroup(
            painelPeriodoColetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelPeriodoColetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(inicioColeta, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                .addComponent(jLabel14))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelPeriodoColetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(fimColeta, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addComponent(jLabel16))
        );

        jLabel28.setText("Situação:"); // NOI18N

        qtTotalBomb.setEditable(false);
        qtTotalBomb.setFont(new java.awt.Font("Tahoma", 1, 65));
        qtTotalBomb.setForeground(new java.awt.Color(255, 0, 0));
        qtTotalBomb.setText("0"); // NOI18N
        qtTotalBomb.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Total de Bombonas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 0, 0))); // NOI18N
        qtTotalBomb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qtTotalBombActionPerformed(evt);
            }
        });

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Bombonas de Contrato", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(0, 0, 0))); // NOI18N

        jLabel38.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel38.setText("20 Litros"); // NOI18N

        jLabel37.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel37.setText("50 Litros"); // NOI18N

        jLabel39.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel39.setText("Qtd.:"); // NOI18N

        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel34.setText("Qtd.:"); // NOI18N

        jLabel35.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel35.setText("200 Litros"); // NOI18N

        jLabel36.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel36.setText("Qtd.:"); // NOI18N

        qtBomb200.setFont(new java.awt.Font("Tahoma", 1, 18));
        qtBomb200.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15" }));
        qtBomb200.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qtBomb200ActionPerformed(evt);
            }
        });

        qtBomb50.setFont(new java.awt.Font("Tahoma", 1, 18));
        qtBomb50.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15" }));
        qtBomb50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qtBomb50ActionPerformed(evt);
            }
        });

        qtBomb20.setFont(new java.awt.Font("Tahoma", 1, 18));
        qtBomb20.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15" }));
        qtBomb20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qtBomb20ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel34)
                        .addComponent(jLabel39))
                    .addComponent(jLabel36))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(qtBomb20, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel38))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(qtBomb200, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(qtBomb50, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel37)
                            .addComponent(jLabel35))))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(qtBomb200, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(qtBomb50, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(qtBomb20, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        painelDiaColeta.setBorder(javax.swing.BorderFactory.createTitledBorder("Dias de Coleta"));

        diaColeta.setEditable(false);
        diaColeta.setFont(new java.awt.Font("Tahoma", 1, 12));

        btAddDiaColeta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/calendario.png"))); // NOI18N
        btAddDiaColeta.setToolTipText("Dias de coleta"); // NOI18N
        btAddDiaColeta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btAddDiaColetanaoMostraFuncionalidadeBotao(evt);
            }
        });
        btAddDiaColeta.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                btAddDiaColetamostraFuncionalidadeBotao(evt);
            }
        });
        btAddDiaColeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddDiaColetaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelDiaColetaLayout = new javax.swing.GroupLayout(painelDiaColeta);
        painelDiaColeta.setLayout(painelDiaColetaLayout);
        painelDiaColetaLayout.setHorizontalGroup(
            painelDiaColetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelDiaColetaLayout.createSequentialGroup()
                .addComponent(diaColeta, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btAddDiaColeta, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        painelDiaColetaLayout.setVerticalGroup(
            painelDiaColetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(diaColeta, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btAddDiaColeta, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        situacaoCli.setEditable(false);
        situacaoCli.setFont(new java.awt.Font("Tahoma", 1, 14));
        situacaoCli.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                situacaoCliMouseClicked(evt);
            }
        });
        situacaoCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                situacaoCliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel28)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(situacaoCli))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(contratoCli, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(painelDiaColeta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(painelPeriodoColeta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(151, 151, 151)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(qtTotalBomb, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(qtTotalBomb, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(contratoCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2))
                            .addComponent(painelDiaColeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(situacaoCli, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                                    .addComponent(jLabel28)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(painelPeriodoColeta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(4, 4, 4)))))
                .addContainerGap())
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        btImprimirFicha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/imprimir.png"))); // NOI18N
        btImprimirFicha.setMnemonic('r');
        btImprimirFicha.setToolTipText("Imprimir ficha do cliente"); // NOI18N
        btImprimirFicha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btImprimirFichaActionPerformed(evt);
            }
        });

        btCancelarCli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/bloquear.png"))); // NOI18N
        btCancelarCli.setMnemonic('e');
        btCancelarCli.setToolTipText("Cancelar cliente"); // NOI18N
        btCancelarCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarCliActionPerformed(evt);
            }
        });

        btAnteriorReg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/anterior.png"))); // NOI18N
        btAnteriorReg.setToolTipText("Registro anterior"); // NOI18N
        btAnteriorReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAnteriorRegActionPerformed(evt);
            }
        });

        btProximoReg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/proximo.png"))); // NOI18N
        btProximoReg.setToolTipText("Próximo registro"); // NOI18N
        btProximoReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btProximoRegActionPerformed(evt);
            }
        });

        btPrimeiroReg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/primeiro.png"))); // NOI18N
        btPrimeiroReg.setToolTipText("Primeiro registro"); // NOI18N
        btPrimeiroReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPrimeiroRegActionPerformed(evt);
            }
        });

        btAddCli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/novoCli.png"))); // NOI18N
        btAddCli.setMnemonic('a');
        btAddCli.setToolTipText("Novo cliente"); // NOI18N
        btAddCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddCliActionPerformed(evt);
            }
        });

        btUltimoReg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ultimo.png"))); // NOI18N
        btUltimoReg.setToolTipText("Último registro"); // NOI18N
        btUltimoReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUltimoRegActionPerformed(evt);
            }
        });

        btGravaCli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/gravar.png"))); // NOI18N
        btGravaCli.setMnemonic('S');
        btGravaCli.setToolTipText("Salvar ou atualizar registro"); // NOI18N
        btGravaCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGravaCliActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/atualiza.png"))); // NOI18N
        jButton1.setToolTipText("Atualizar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        caixaPesquisaNome.setFont(new java.awt.Font("Tahoma", 1, 14));
        caixaPesquisaNome.setForeground(new java.awt.Color(0, 0, 153));
        caixaPesquisaNome.setToolTipText("Digite as iniciais do nome do cliente");
        caixaPesquisaNome.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nome / Razão social ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12), new java.awt.Color(255, 51, 0))); // NOI18N
        caixaPesquisaNome.setSelectionColor(new java.awt.Color(0, 0, 204));
        caixaPesquisaNome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                caixaPesquisaNomeMouseClicked(evt);
            }
        });
        caixaPesquisaNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caixaPesquisaNomeActionPerformed(evt);
            }
        });
        caixaPesquisaNome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                caixaPesquisaNomeFocusGained(evt);
            }
        });

        caixaPesquisaContrato.setFont(new java.awt.Font("Tahoma", 1, 14));
        caixaPesquisaContrato.setToolTipText("Digite o n° do contrato completo do cliente");
        caixaPesquisaContrato.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "N° Contrato", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12), new java.awt.Color(255, 51, 0))); // NOI18N
        caixaPesquisaContrato.setSelectionColor(new java.awt.Color(0, 0, 204));
        caixaPesquisaContrato.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                caixaPesquisaContratoMouseClicked(evt);
            }
        });
        caixaPesquisaContrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caixaPesquisaContratoActionPerformed(evt);
            }
        });
        caixaPesquisaContrato.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                caixaPesquisaContratoFocusGained(evt);
            }
        });

        btExcluirCli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/excluir.png"))); // NOI18N
        btExcluirCli.setMnemonic('a');
        btExcluirCli.setToolTipText("Excluir registro"); // NOI18N
        btExcluirCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirCliActionPerformed(evt);
            }
        });

        selecaoSituacao.add(btAtivos);
        btAtivos.setSelected(true);
        btAtivos.setText("Ativos");
        btAtivos.setToolTipText("Ativos");
        btAtivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAtivosActionPerformed(evt);
            }
        });

        selecaoSituacao.add(btCancelados);
        btCancelados.setText("Cancelados");
        btCancelados.setToolTipText("Cancelados");
        btCancelados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCanceladosActionPerformed(evt);
            }
        });

        selecaoSituacao.add(btSuspensosDeterminados);
        btSuspensosDeterminados.setText("Susp. deter");
        btSuspensosDeterminados.setToolTipText("Suspensos");
        btSuspensosDeterminados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSuspensosDeterminadosActionPerformed(evt);
            }
        });

        selecaoSituacao.add(btTodos);
        btTodos.setText("Todos");
        btTodos.setToolTipText("Todos");
        btTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTodosActionPerformed(evt);
            }
        });

        btSuspenderCli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/sus_cliente.png"))); // NOI18N
        btSuspenderCli.setMnemonic('e');
        btSuspenderCli.setToolTipText("Suspender cliente"); // NOI18N
        btSuspenderCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSuspenderCliActionPerformed(evt);
            }
        });

        btImprimirLista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/imprimir22.png"))); // NOI18N
        btImprimirLista.setText("Imprimir lista");
        btImprimirLista.setToolTipText("Imprimir lista de clientes");
        btImprimirLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btImprimirListaActionPerformed(evt);
            }
        });

        selecaoSituacao.add(btSuspensosIndeterminados);
        btSuspensosIndeterminados.setText("Susp. indet");
        btSuspensosIndeterminados.setToolTipText("Suspensos");
        btSuspensosIndeterminados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSuspensosIndeterminadosActionPerformed(evt);
            }
        });

        infoSituacao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/informacaoCli.png"))); // NOI18N
        infoSituacao.setToolTipText("Informação de situação"); // NOI18N
        infoSituacao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                infoSituacaonaoMostraFuncionalidadeBotao(evt);
            }
        });
        infoSituacao.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                infoSituacaomostraFuncionalidadeBotao(evt);
            }
        });
        infoSituacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoSituacaoActionPerformed(evt);
            }
        });

        listaClientes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                listaClientesKeyTyped(evt);
            }
        });

        btSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/sair.png"))); // NOI18N
        btSair.setMnemonic('e');
        btSair.setToolTipText("Sair"); // NOI18N
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        lbQtdCli.setText("0 Cliente(s)");

        grupoSituacaoSusDeter.add(rb_emDia);
        rb_emDia.setSelected(true);
        rb_emDia.setText("Em dia");
        rb_emDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_emDiaActionPerformed(evt);
            }
        });
        rb_emDia.setVisible(false);

        grupoSituacaoSusDeter.add(rb_vencidos);
        rb_vencidos.setText("Vencidos");
        rb_vencidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_vencidosActionPerformed(evt);
            }
        });
        rb_vencidos.setVisible(false);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(btPrimeiroReg, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btAnteriorReg, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btTodos, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(btProximoReg, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btUltimoReg, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btAtivos, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(btGravaCli, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btAddCli, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btSuspensosDeterminados, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(btSuspenderCli, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btCancelarCli, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btSuspensosIndeterminados, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(infoSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btImprimirFicha, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btCancelados, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(btExcluirCli, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btSair, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btImprimirLista, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(caixaPesquisaNome, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(listaClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbQtdCli, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(caixaPesquisaContrato, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(rb_emDia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rb_vencidos)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER, false)
                                .addComponent(btProximoReg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btUltimoReg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(btPrimeiroReg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btAnteriorReg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER, false)
                                .addComponent(btSuspenderCli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btCancelarCli)
                                .addComponent(btImprimirFicha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btExcluirCli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1)
                                .addComponent(infoSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(caixaPesquisaContrato, 0, 0, Short.MAX_VALUE)
                                .addComponent(caixaPesquisaNome, 0, 41, Short.MAX_VALUE)
                                .addComponent(btSair))))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER, false)
                            .addComponent(btGravaCli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btAddCli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(listaClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbQtdCli)
                            .addComponent(rb_emDia)
                            .addComponent(rb_vencidos)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btImprimirLista, 0, 0, Short.MAX_VALUE)
                            .addComponent(btCancelados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btSuspensosIndeterminados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btSuspensosDeterminados, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btTodos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btAtivos))))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        java.awt.Dimension dialogSize = getSize();
        setLocation((screenSize.width-dialogSize.width)/2,(screenSize.height-dialogSize.height)/2);
    }// </editor-fold>//GEN-END:initComponents

    private void contratoCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contratoCliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contratoCliActionPerformed

    private void ruaCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ruaCliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ruaCliActionPerformed

    private void ptReferenciaCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ptReferenciaCliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ptReferenciaCliActionPerformed

    private void responsavelCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_responsavelCliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_responsavelCliActionPerformed

    private void btAddDiaColetanaoMostraFuncionalidadeBotao(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btAddDiaColetanaoMostraFuncionalidadeBotao
        // TODO add your handling code here:
    }//GEN-LAST:event_btAddDiaColetanaoMostraFuncionalidadeBotao

    private void btAddDiaColetamostraFuncionalidadeBotao(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_btAddDiaColetamostraFuncionalidadeBotao
        // TODO add your handling code here:
    }//GEN-LAST:event_btAddDiaColetamostraFuncionalidadeBotao

    private void btAddDiaColetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddDiaColetaActionPerformed
        validaCadCli.diaColeta();
    }//GEN-LAST:event_btAddDiaColetaActionPerformed

    private void infoSituacaonaoMostraFuncionalidadeBotao(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_infoSituacaonaoMostraFuncionalidadeBotao
        // TODO add your handling code here:
    }//GEN-LAST:event_infoSituacaonaoMostraFuncionalidadeBotao

    private void infoSituacaomostraFuncionalidadeBotao(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_infoSituacaomostraFuncionalidadeBotao
        // TODO add your handling code here:
    }//GEN-LAST:event_infoSituacaomostraFuncionalidadeBotao

    private void infoSituacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoSituacaoActionPerformed
        //busca informação na classe validaCadCli
        validaCadCli.botaoInformaSituacao();
    }//GEN-LAST:event_infoSituacaoActionPerformed

    private void codigoCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigoCliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codigoCliActionPerformed

    private void qtTotalBombActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qtTotalBombActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qtTotalBombActionPerformed

    private void btAddCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddCliActionPerformed
        if(gravandoCliente == true && nomeCli.getText().length() > 0 ){
            int opc = JOptionPane.showConfirmDialog(null, "O registro atual será apagado. Deseja continuar?", "Aviso", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);

            if(opc == JOptionPane.YES_OPTION){
                validaCadCli.novoCliente();
//                fecharCamposDePesquisa();
            }
            
            else
               return;
        }
        else{
            validaCadCli.novoCliente();
//            fecharCamposDePesquisa();
        }
    }//GEN-LAST:event_btAddCliActionPerformed

    private void caixaPesquisaContratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caixaPesquisaContratoActionPerformed
        validaCadCli.pesquisarClienteContrato();
    }//GEN-LAST:event_caixaPesquisaContratoActionPerformed

    private void qtBomb200ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qtBomb200ActionPerformed
        //cada seleção soma logo as três caixas
        validaCadCli.calculaTotalBomb();

    }//GEN-LAST:event_qtBomb200ActionPerformed

    private void qtBomb50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qtBomb50ActionPerformed
        //cada seleção soma logo as três caixas
        validaCadCli.calculaTotalBomb();
    }//GEN-LAST:event_qtBomb50ActionPerformed

    private void qtBomb20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qtBomb20ActionPerformed
        //cada seleção soma logo as três caixas
        validaCadCli.calculaTotalBomb();
    }//GEN-LAST:event_qtBomb20ActionPerformed

    private void btGravaCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGravaCliActionPerformed
        //se cancelado ou suspenso não atualiza
        if(situacaoCli.getText().equals("CANCELADO") || situacaoCli.getText().equals("SUSPENSO"))
            JOptionPane.showMessageDialog(null, "Impossível atualizar registro porque o cliente está "+situacaoCli.getText().toLowerCase()+"!", "Aviso", JOptionPane.WARNING_MESSAGE);
        else
            validaCadCli.atualizar_ou_gravar();
    }//GEN-LAST:event_btGravaCliActionPerformed

    private void btPrimeiroRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPrimeiroRegActionPerformed
                //posição do registro
                validaCadCli.direcao = "primeiro";
                //chama o metodo que resolve a navegação dos botoes
                validaCadCli.navega();
                gravandoCliente = false;
    }//GEN-LAST:event_btPrimeiroRegActionPerformed

    private void btExcluirCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirCliActionPerformed
      if(codigoCli.getText().isEmpty())
          JOptionPane.showMessageDialog(null, "Selecione um registro através dos botões de navegação", "Aviso", JOptionPane.WARNING_MESSAGE);
      else
          validaCadCli.excluirRegistro();

    }//GEN-LAST:event_btExcluirCliActionPerformed

    private void btAnteriorRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAnteriorRegActionPerformed

                navega = 1;
                //posição do registro
                validaCadCli.direcao = "anterior";
                //chama o metodo que resolve a navegação dos botoes
                validaCadCli.navega();
                gravandoCliente = false;

    }//GEN-LAST:event_btAnteriorRegActionPerformed

    private void btProximoRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btProximoRegActionPerformed

                navega = 2;
                //posição do registro
                validaCadCli.direcao = "proximo";
                //chama o metodo que resolve a navegação dos botoes
                validaCadCli.navega();
                gravandoCliente = false;

    }//GEN-LAST:event_btProximoRegActionPerformed

    private void btUltimoRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUltimoRegActionPerformed

                //posição do registro
                validaCadCli.direcao = "ultimo";
                //chama o metodo que resolve a navegação dos botoes
                validaCadCli.navega();
                gravandoCliente = false;

    }//GEN-LAST:event_btUltimoRegActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        //pergunta
        int opcao = JOptionPane.showConfirmDialog(null , "Deseja realmente sair?", "Sair", JOptionPane.YES_NO_OPTION);

        if(opcao == JOptionPane.YES_OPTION){
            //chama o metdo para fechar a conexao
            validaCadCli.fechaConexao();
            dispose();
        }
        else
            return;
    }//GEN-LAST:event_formWindowClosing

    private void orderNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderNomeActionPerformed

            validaCadCli.ordenacao("nome_cli");
    }//GEN-LAST:event_orderNomeActionPerformed

    private void orderCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderCodigoActionPerformed

            validaCadCli.ordenacao("cod_cli");
    }//GEN-LAST:event_orderCodigoActionPerformed

    private void orderBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderBairroActionPerformed
            validaCadCli.ordenacao("bairro");
    }//GEN-LAST:event_orderBairroActionPerformed

    private void btAtivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAtivosActionPerformed
 
            rb_emDia.setVisible(false);
            rb_vencidos.setVisible(false);
            
        validaCadCli.vizualizacaoSituacao("'ATIVO'");

    }//GEN-LAST:event_btAtivosActionPerformed

    private void btCanceladosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCanceladosActionPerformed

           rb_emDia.setVisible(false);
           rb_vencidos.setVisible(false);

        validaCadCli.vizualizacaoSituacao("'CANCELADO'");

    }//GEN-LAST:event_btCanceladosActionPerformed

    private void btSuspensosDeterminadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSuspensosDeterminadosActionPerformed
           //SELECIONA E EM DIA MOSTRA OS RADIO BUTTONS EM DIA e VENCIDOS.
           rb_emDia.setSelected(true);
           rb_emDia.setVisible(true);
           rb_vencidos.setVisible(true);

        validaCadCli.vizualizacaoSituacao("'SUSPENSO' and dia_retorno != '0000-00-00' and dia_retorno > '"+validaLogin.DATAFORMAT+"'");
    
    }//GEN-LAST:event_btSuspensosDeterminadosActionPerformed

    private void btTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTodosActionPerformed
           validaCadCli.vizualizacaoSituacao("'ATIVO' or situacao = 'SUSPENSO' or situacao = 'CANCELADO'");

           rb_emDia.setVisible(false);
           rb_vencidos.setVisible(false);
    }//GEN-LAST:event_btTodosActionPerformed

    private void caixaPesquisaNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caixaPesquisaNomeActionPerformed
        validaCadCli.pesquisarClienteNome();
    }//GEN-LAST:event_caixaPesquisaNomeActionPerformed

    private void caixaPesquisaNomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_caixaPesquisaNomeMouseClicked
        caixaPesquisaContrato.setText("");
    }//GEN-LAST:event_caixaPesquisaNomeMouseClicked

    private void caixaPesquisaContratoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_caixaPesquisaContratoMouseClicked
        caixaPesquisaNome.setText("");
    }//GEN-LAST:event_caixaPesquisaContratoMouseClicked

    private void caixaPesquisaContratoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_caixaPesquisaContratoFocusGained
        caixaPesquisaNome.setText("");
    }//GEN-LAST:event_caixaPesquisaContratoFocusGained

    private void caixaPesquisaNomeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_caixaPesquisaNomeFocusGained
        caixaPesquisaContrato.setText("");
    }//GEN-LAST:event_caixaPesquisaNomeFocusGained

    private void btSuspenderCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSuspenderCliActionPerformed
        validaCadCli.validaCampos();

        //se grava for verdadeiro(gravou no bd);
        if(validaCadCli.grava == true)
            validaCadCli.btSuspenderCliente();
        else
           return;

    }//GEN-LAST:event_btSuspenderCliActionPerformed

    private void btCancelarCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarCliActionPerformed
        validaCadCli.validaCampos();

        //se grava for verdadeiro(gravou no bd);
        if(validaCadCli.grava == true)
            validaCadCli.btCancelarCliente();
        else
            return;
    }//GEN-LAST:event_btCancelarCliActionPerformed

    private void situacaoCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_situacaoCliActionPerformed
        validaCadCli.btMostraInfo();
    }//GEN-LAST:event_situacaoCliActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(codigoCli.getText().isEmpty() && nomeCli.getText().length() > 0){
            int opc = JOptionPane.showConfirmDialog(null, "O registro atual será apagado. Deseja continuar?", "Aviso", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);

            if(opc == JOptionPane.YES_OPTION)
               validaCadCli.atualizar();

            else
               return;
        }
        else
              validaCadCli.atualizar();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tabelaClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaClienteMouseClicked
        if(codigoCli.getText().isEmpty()){
            int opc = JOptionPane.showConfirmDialog(null, "O registro atual será subistituído pelo registro que você clicou. Deseja continuar?", "Aviso", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);

            if(opc == JOptionPane.YES_OPTION)
                validaCadCli.cliqueGrid();

            else{
               codigoCli.requestFocus();
               return;
            }
        }
        else
            validaCadCli.cliqueGrid();
    }//GEN-LAST:event_tabelaClienteMouseClicked

    private void tabelaClienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabelaClienteKeyReleased
        validaCadCli.cliqueGrid();
    }//GEN-LAST:event_tabelaClienteKeyReleased

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        //pergunta
        int opcao = JOptionPane.showConfirmDialog(null , "Deseja realmente sair?", "Sair", JOptionPane.YES_NO_OPTION);

        if(opcao == JOptionPane.YES_OPTION){
            //chama o metdo para fechar a conexao
            validaCadCli.fechaConexao();
            dispose();
        } else
            return;
    }//GEN-LAST:event_btSairActionPerformed

    private void situacaoCliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_situacaoCliMouseClicked
       if(evt.getClickCount() == 5)
           situacaoCli.setText("ATIVO");
    }//GEN-LAST:event_situacaoCliMouseClicked

    private void btImprimirListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btImprimirListaActionPerformed

        if(situacaoCli.getText().equals("ATIVO") && btAtivos.isSelected())
           new clientesAtivos();
        else if(situacaoCli.getText().equals("SUSPENSO") && btSuspensosDeterminados.isSelected() && rb_emDia.isSelected())
           new clientesSuspensos();
        else if(situacaoCli.getText().equals("SUSPENSO") && btSuspensosDeterminados.isSelected() && rb_vencidos.isSelected())
            new relacaoSuspensosVencidos();
        else if(situacaoCli.getText().equals("SUSPENSO") && btSuspensosIndeterminados.isSelected())
            new clientesSuspensosIndeterminados();
        else if(situacaoCli.getText().equals("CANCELADO") && btCancelados.isSelected())
           new clientesCancelados();
        else
           JOptionPane.showMessageDialog(null, "Selecione uma das três situações para imprimir a lista de clientes.\nCada situação contém campos específicos quando gerado o documento para impressão", "Aviso", JOptionPane.WARNING_MESSAGE);

    }//GEN-LAST:event_btImprimirListaActionPerformed

    private void btImprimirFichaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btImprimirFichaActionPerformed

        if(situacaoCli.getText().equals("ATIVO"))
           new clienteAtivo();
        else if(situacaoCli.getText().equals("SUSPENSO") && btSuspensosDeterminados.isSelected() && rb_emDia.isSelected())
           new relacaoSuspenso();
        else if(situacaoCli.getText().equals("SUSPENSO") && btSuspensosDeterminados.isSelected() && rb_vencidos.isSelected())
           new relacaoSuspensoVencido();
        else if(situacaoCli.getText().equals("SUSPENSO") && btSuspensosIndeterminados.isSelected())
            new clienteSuspensoIndeterminado();
        else if(situacaoCli.getText().equals("CANCELADO"))
           new clienteCancelado();
        else
           JOptionPane.showMessageDialog(null, "selecione um registro para impressão", "Aviso", JOptionPane.WARNING_MESSAGE);


    }//GEN-LAST:event_btImprimirFichaActionPerformed

    private void ufCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ufCliActionPerformed

    }//GEN-LAST:event_ufCliActionPerformed

    private void addBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBairroActionPerformed
        //permissão para atualizar a tela de clientes se o usuário solicitar o cadastramento de bairro da propria tela de clientes
        validaCadCli.atualizaDadosManutencao = true;

        if(validaLogin.USUARIO.equals("Gerente")){
            cadastro_bairro cadBairro = new cadastro_bairro(new javax.swing.JFrame(), true);
            cadBairro.tf_cod.setText("");
            cadBairro.tf_nome.setEditable(true);
            cadBairro.tf_nome.setText("");
            cadBairro.tf_nome.requestFocus();
            cadBairro.btExcluir.setVisible(false);
            cadBairro.habilitaBotoes(false);
            cadBairro.setVisible(true);

        }
        else if(validaLogin.USUARIO.equals("Administrador"))
            new cadastro_bairro(new javax.swing.JFrame(), true).setVisible(true);


    }//GEN-LAST:event_addBairroActionPerformed

    private void addCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCidadeActionPerformed
        //permissão para atualizar a tela de clientes se o usuário solicitar o cadastramento da propria tela
        validaCadCli.atualizaDadosManutencao = true;

        if(validaLogin.USUARIO.equals("Gerente")){
            cadastro_cidade cadCidade = new cadastro_cidade(new javax.swing.JFrame(), true);
            cadCidade.tf_cod.setText("");
            cadCidade.tf_nome.setEditable(true);
            cadCidade.tf_nome.setText("");
            cadCidade.tf_nome.requestFocus();
            cadCidade.btExcluir.setVisible(false);
            cadCidade.habilitaBotoes(false);
            cadCidade.setVisible(true);

        }
        else if(validaLogin.USUARIO.equals("Administrador"))
            new cadastro_cidade(new javax.swing.JFrame(), true).setVisible(true);
    }//GEN-LAST:event_addCidadeActionPerformed

    private void contratoCliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contratoCliMouseClicked

        if(evt.getClickCount() == 3 && contratoCli.getText().length() > 0){

            contratoCli.setEditable(true);
            contratoCli.setEnabled(true);
            validaCadCli.naoDeixaAleterarContrato();


        }
    }//GEN-LAST:event_contratoCliMouseClicked

    private void nomeCliKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nomeCliKeyTyped
        validaCadCli.habilitaBotoesOrganizacaoSituacao();
    }//GEN-LAST:event_nomeCliKeyTyped

    private void btSuspensosIndeterminadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSuspensosIndeterminadosActionPerformed

           rb_emDia.setVisible(false);
           rb_vencidos.setVisible(false);
           
        validaCadCli.vizualizacaoSituacao("'SUSPENSO' and dia_retorno = '0000-00-00'");

    }//GEN-LAST:event_btSuspensosIndeterminadosActionPerformed

    private void listaClientesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_listaClientesKeyTyped
        validaCadCli.mostraClienteDaListaDeSelecao();
    }//GEN-LAST:event_listaClientesKeyTyped

    private void rb_vencidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_vencidosActionPerformed
        validaCadCli.vizualizacaoSituacao("'SUSPENSO' and dia_retorno != '0000-00-00' and dia_retorno <= '"+validaLogin.DATAFORMAT+"'");
    }//GEN-LAST:event_rb_vencidosActionPerformed

    private void rb_emDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_emDiaActionPerformed
        validaCadCli.vizualizacaoSituacao("'SUSPENSO' and dia_retorno != '0000-00-00' and dia_retorno > '"+validaLogin.DATAFORMAT+"'");
    }//GEN-LAST:event_rb_emDiaActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroCliente().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton addBairro;
    public static javax.swing.JButton addCidade;
    public static javax.swing.JComboBox bairroCli;
    public static javax.swing.ButtonGroup botoesOrdenacao;
    public static javax.swing.JButton btAddCli;
    public static javax.swing.JButton btAddDiaColeta;
    public static javax.swing.JButton btAnteriorReg;
    public static javax.swing.JToggleButton btAtivos;
    public static javax.swing.JToggleButton btCancelados;
    public static javax.swing.JButton btCancelarCli;
    public static javax.swing.JButton btExcluirCli;
    public static javax.swing.JButton btGravaCli;
    public static javax.swing.JButton btImprimirFicha;
    public static javax.swing.JButton btImprimirLista;
    public static javax.swing.JButton btPrimeiroReg;
    public static javax.swing.JButton btProximoReg;
    private javax.swing.JButton btSair;
    public static javax.swing.JButton btSuspenderCli;
    public static javax.swing.JToggleButton btSuspensosDeterminados;
    public static javax.swing.JToggleButton btSuspensosIndeterminados;
    public static javax.swing.JToggleButton btTodos;
    public static javax.swing.JButton btUltimoReg;
    public static javax.swing.JTextField caixaPesquisaContrato;
    public static javax.swing.JTextField caixaPesquisaNome;
    public static javax.swing.JComboBox cidadeCli;
    public static javax.swing.JTextField codigoCli;
    public static javax.swing.JTextField contratoCli;
    public static javax.swing.JTextField diaColeta;
    public static javax.swing.JComboBox fimColeta;
    public static javax.swing.JFormattedTextField foneCli;
    private javax.swing.ButtonGroup grupoSituacaoSusDeter;
    public static javax.swing.JFormattedTextField hrFun_de;
    public static javax.swing.JFormattedTextField hrFunc_a;
    public static javax.swing.JButton infoSituacao;
    public static javax.swing.JComboBox inicioColeta;
    public static javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    public static javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    public static javax.swing.JLabel lbQtdCli;
    public static javax.swing.JComboBox listaClientes;
    public static javax.swing.JTextField nomeCli;
    public static javax.swing.JTextField obs;
    public static javax.swing.JRadioButton orderBairro;
    public static javax.swing.JRadioButton orderCodigo;
    public static javax.swing.JRadioButton orderNome;
    public static javax.swing.JPanel painelDiaColeta;
    public static javax.swing.JPanel painelPeriodoColeta;
    public static javax.swing.JTextField ptReferenciaCli;
    public static javax.swing.JComboBox qtBomb20;
    public static javax.swing.JComboBox qtBomb200;
    public static javax.swing.JComboBox qtBomb50;
    public static javax.swing.JTextField qtTotalBomb;
    public static javax.swing.JRadioButton rb_emDia;
    public static javax.swing.JRadioButton rb_vencidos;
    public static javax.swing.JTextField responsavelCli;
    public static javax.swing.JTextField ruaCli;
    private javax.swing.ButtonGroup selecaoSituacao;
    public static javax.swing.JTextField situacaoCli;
    public static javax.swing.JTable tabelaCliente;
    public static javax.swing.JComboBox ufCli;
    // End of variables declaration//GEN-END:variables


//    public void fecharCamposDePesquisa(){
//
//        //esconde campos de texto
//        caixaPesquisaContrato.setVisible(false);
//        caixaPesquisaNome.setVisible(false);
//        btLimpaCampo.setVisible(false);
//
//        //esconde botoes
//        btVer.setVisible(false);
//        btFechaPesq.setVisible(false);
//
//        //limpa campos
//        caixaPesquisaContrato.setText("");
//        caixaPesquisaNome.setText("");
//
//
//    }

}
